{
  "hash": "a462c4ce6058d5962db476c4100635f7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Inference conclusion\"\nsubtitle: \"Lecture 22\"\ndate: \"2025-4-14\"\nformat: revealjs\nauto-stretch: false\n---\n\n# Recap: statistical inference\n\n\n::: {.cell}\n\n:::\n\n\n## Point estimation: what's your best guess? {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mtcars, aes(x = wt, y = mpg)) + \n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n## Point estimation: what's your best guess? {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() |>\n  fit(mpg ~ wt, data = mtcars) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    37.3      1.88      19.9  8.24e-19\n2 wt             -5.34     0.559     -9.56 1.29e-10\n```\n\n\n:::\n:::\n\n\n## Sampling variability\n\nDifferent data \\>\\> Different estimate.\nBut how different?\n\n-   **Reassuring**: recompute your estimate on other data and get basically the same answer.\n    Sampling variation is low.\n    Uncertainty is low.\n    Results are more reliable;\n\n-   **Concerning**: recompute your estimate on new data and get a wildly different answer.\n    Sampling variation is high.\n    Uncertainty is high.\n    Results are less reliable.\n\nHow do we operationalize this?\n\n## The bootstrap\n\nConstruct different, alternative datasets by sampling *with replacement* from your original data.\nEach bootstrap sample gives you a different estimate, and you can see how vigorously they wiggle around:\n\n\n::: {.cell}\n\n:::\n\n\n::: columns\n::: {.column width=\"49%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n:::\n\n::: {.column width=\"49%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## Interval estimation\n\nUse the bootstrap distribution to construct a range of likely values for the unknown parameter:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\nWe use quantiles (think IQR), but there are other ways.\n\n## Hypothesis testing {.smaller}\n\n::: incremental\n-   Two competing claims about $\\beta_1$: $$\n    \\begin{aligned}\n    H_0&: \\beta_1=0\\quad(\\text{nothing going on})\\\\\n    H_A&: \\beta_1\\neq0\\quad(\\text{something going on})\n    \\end{aligned}\n    $$\n\n-   Do the data strongly favor one or the other?\n\n-   How can we quantify this? p-values!\n:::\n\n## *p*-value {.scrollable}\n\n*p*-value is the fraction of the histogram area shaded red:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n\n## Discernibility level {.scrollable}\n\n::: incremental\n-   How do we decide if the *p*-value is big enough or small enough?\n\n-   Pick a threshold $\\alpha\\in[0,\\,1]$ called the *discernibility level*:\n\n    -   If $p\\text{-value} < \\alpha$, reject null and accept alternative;\n    -   If $p\\text{-value} \\geq \\alpha$, fail to reject null;\n\n-   Standard choices: $\\alpha=0.01, 0.05, 0.1, 0.15$.\n:::\n\n## AE 17 Recap\n\n::: incremental\n-   **Goal**: Predicting mean household income using the percent of a county that is uninsured\n\n-   We did inference with `counties_sample`, a small sample of 25 counties in the US\n:::\n\n## Point Estimate {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_fit <- counties_sample |>\n  specify(mean_household_income ~ uninsured) |>\n  fit()\n\nobserved_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  term      estimate\n  <chr>        <dbl>\n1 intercept   79489.\n2 uninsured    -884.\n```\n\n\n:::\n:::\n\n\n## Generating the null distribution {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist <- counties_sample |>\n  specify(mean_household_income ~ uninsured) |>\n  hypothesize(null = \"independence\") |>\n  generate(reps = 1000, type = \"permute\") |>\n  fit()\n\nnull_dist |> \n  filter(term == \"uninsured\") |>\n  ggplot(aes(x = estimate)) + \n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n## How does this work? {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist <- counties_sample |>\n  specify(mean_household_income ~ uninsured) |>\n  hypothesize(null = \"independence\") |>\n  generate(reps = 1000, type = \"permute\") |>\n  fit()\n\nnull_dist\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,000 × 3\n# Groups:   replicate [1,000]\n   replicate term      estimate\n       <int> <chr>        <dbl>\n 1         1 intercept  73680. \n 2         1 uninsured   -279. \n 3         2 intercept  71343. \n 4         2 uninsured    -35.3\n 5         3 intercept  69869. \n 6         3 uninsured    118. \n 7         4 intercept  62820. \n 8         4 uninsured    853. \n 9         5 intercept  84203. \n10         5 uninsured  -1376. \n# ℹ 1,990 more rows\n```\n\n\n:::\n:::\n\n\n## How does this work? {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2\"}\nnull_dist <- counties_sample |>\n  specify(mean_household_income ~ uninsured) |>\n  hypothesize(null = \"independence\") |>\n  generate(reps = 1000, type = \"permute\") |>\n  fit()\n```\n:::\n\n\n## How does this work? {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"3\"}\nnull_dist <- counties_sample |>\n  specify(mean_household_income ~ uninsured) |>\n  hypothesize(null = \"independence\") |>\n  generate(reps = 1000, type = \"permute\") |>\n  fit()\n```\n:::\n\n\n## How does this work? {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"4\"}\nnull_dist <- counties_sample |>\n  specify(mean_household_income ~ uninsured) |>\n  hypothesize(null = \"independence\") |>\n  generate(reps = 1000, type = \"permute\") |>\n  fit()\n```\n:::\n\n\n## What is happening? {.smaller}\n\n::: incremental\n-   Recall: Bootstrapping for confidence intervals\n\n    -   We created a bunch of new data sets by **resampling** from our original data set\n\n    -   We computed an estimate for each new data set\n\n-   Here:\n\n    -   We are creating a bunch of new data sets by **permuting** our original data set and computing an estimate for each\n\n    -   Instead of attempting to mimic samples from the population data (like boostrapping), we are attempting to mimic samples from the *null*\n:::\n\n## So what does \"permuting\" do? {.smaller}\n\nWe are simulating what the world would look like *if* the **null hypothesis were true**: what if `mean_household_income` and `uninsured` are unrelated?\n\n::: incremental\n-   We **randomly shuffle** the values of the response variable: `mean_household_income`\n-   We **leave** the explanatory variable (`uninsured`) unchanged\n-   We do this many times (e.g. `reps = 1000`)\n-   Each time we calculate the slope from the new fake dataset\n:::\n\n## Small permutation example: {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n**Original:**\n\n| Uninsured (%) | Mean Income (\\$k) |\n|---------------|-------------------|\n| 5             | 70                |\n| 8             | 65                |\n| 6             | 68                |\n| 7             | 66                |\n| 9             | 64                |\n:::\n\n::: {.column width=\"50%\"}\n:::\n:::\n\n## Small permutation example: {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n**Original:**\n\n| Uninsured (%) | Mean Income (\\$k) |\n|---------------|-------------------|\n| 5             | 70                |\n| 8             | 65                |\n| 6             | 68                |\n| 7             | 66                |\n| 9             | 64                |\n:::\n\n::: {.column width=\"50%\"}\n**Permutation 1:**\n\n| Uninsured (%) | Mean Income (\\$k) |\n|---------------|-------------------|\n| 8             | 70                |\n| 5             | 65                |\n| 7             | 68                |\n| 9             | 66                |\n| 6             | 64                |\n\n:::\n:::\n\n## Small permutation example: {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n**Original:**\n\n| Uninsured (%) | Mean Income (\\$k) |\n|---------------|-------------------|\n| 5             | 70                |\n| 8             | 65                |\n| 6             | 68                |\n| 7             | 66                |\n| 9             | 64                |\n:::\n\n::: {.column width=\"50%\"}\n**Permutation 2:**\n\n| Uninsured (%) | Mean Income (\\$k) |\n|---------------|-------------------|\n| 5             | 70                |\n| 7             | 65                |\n| 9             | 68                |\n| 8             | 66                |\n| 6             | 64                |\n\n:::\n:::\n\n. . . \n\nDo this `reps` times; make a histogram of slope estimates!\n\n## Null distribution {.smaller}\n\nThe null distribution shows the plot of \n\n::: {.cell}\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n\n\n## Then what? {.smaller}\n\nCompare the slope from the original data set to our null distribution!\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n\n## Better code {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisualize(null_dist) +\n  shade_p_value(obs_stat = observed_fit, direction = \"two-sided\")\n```\n\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/shade-p-value-1.png){width=960}\n:::\n:::\n\n\n\n## The p-value {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist |>\n  get_p_value(obs_stat = observed_fit, direction = \"two-sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  term      p_value\n  <chr>       <dbl>\n1 intercept   0.138\n2 uninsured   0.138\n```\n\n\n:::\n:::\n\n\n\n## Recap: Hypothesis testing {.smaller}\n\n::: incremental\n-   Think hypothetically: if the null hypothesis were in fact true, would my results be out of the ordinary?\n\n    -   if no, then the null could be true;\n    -   if yes, then the null might be bogus;\n\n-   My results represent the reality of actual data.\n    If they conflict with the null, then you throw out the null and stick with reality;\n\n-   How do we *quantify* \"would my results be out of the ordinary\"?\n:::\n\n## Idea: Hypothesis test for a difference in means {.smaller}\n\nWhat if I want to test if the means of two groups are actually different from each other? \n\n:::incremental\n- Is the mean household income different in counties that vote red vs. blue?\n- Do athletes who train over a certain number of hours a day have better performance (measured by some metric) than those who train under that number?\n- Do babies born to mothers who smoke have lower body weights than non-smoking mothers?\n\n:::\n\n## Example: smoking/non-smoking mothers {.smaller}\n\nA random sample of US births from 2014:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(births14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{style='font-size: 0.6em'}\nRows: 1,000\nColumns: 13\n$ fage           <int> 34, 36, 37, NA, 32, 32, 37, 29, 30, 29, 30, 3…\n$ mage           <dbl> 34, 31, 36, 16, 31, 26, 36, 24, 32, 26, 34, 2…\n$ mature         <chr> \"younger mom\", \"younger mom\", \"mature mom\", \"…\n$ weeks          <dbl> 37, 41, 37, 38, 36, 39, 36, 40, 39, 39, 42, 4…\n$ premie         <chr> \"full term\", \"full term\", \"full term\", \"full …\n$ visits         <dbl> 14, 12, 10, NA, 12, 14, 10, 13, 15, 11, 14, 1…\n$ gained         <dbl> 28, 41, 28, 29, 48, 45, 20, 65, 25, 22, 40, 3…\n$ weight         <dbl> 6.96, 8.86, 7.51, 6.19, 6.75, 6.69, 6.13, 6.7…\n$ lowbirthweight <chr> \"not low\", \"not low\", \"not low\", \"not low\", \"…\n$ sex            <chr> \"male\", \"female\", \"female\", \"male\", \"female\",…\n$ habit          <chr> \"nonsmoker\", \"nonsmoker\", \"nonsmoker\", \"nonsm…\n$ marital        <chr> \"married\", \"married\", \"married\", \"not married…\n$ whitemom       <chr> \"white\", \"white\", \"not white\", \"white\", \"whit…\n```\n\n\n:::\n:::\n\n\nDo babies born to mothers who smoke have lower body weights than non-smoking mothers?\n\n## Visualize {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirths14 <- births14 |> drop_na(weight, habit) \nbirths14 |>\n  ggplot(aes(x = weight, y = habit)) + \n  geom_boxplot(alpha = 0.5) + \n  labs(\n    x = \"Birth Weight (lbs)\",\n    y = \"Mother smoking status\"\n  )\n```\n\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-20-1.png){width=960}\n:::\n:::\n\n\n## Estimate {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() |>\n  fit(weight ~ habit, data = births14) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic    p.value\n  <chr>          <dbl>     <dbl>     <dbl>      <dbl>\n1 (Intercept)    7.27     0.0435    167.   0         \n2 habitsmoker   -0.593    0.128      -4.65 0.00000382\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{weight}=7.27-0.59\\times \\texttt{smoker}.\n$$\n\n## Remember... {.smaller}\n\n$$\n\\widehat{weight}=7.27-0.59\\times \\texttt{smoker}.\n$$\n\n::: incremental\n-   `habit` is categorical with two levels: `smoker` and `non-smoker`.\n\n-   The baseline is `non-smoker`, with $$\n    \\widehat{weight} = 7.27;\n    $$\n\n-   The smoking group has `smoker = 1`, so $$\n    \\widehat{weight} = 7.27 - 0.59 = 6.68.\n    $$\n:::\n\n## Those were not magic numbers {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirths14 |>\n  group_by(habit) |>\n  summarize(\n    mean_weight = mean(weight)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  habit     mean_weight\n  <chr>           <dbl>\n1 nonsmoker        7.27\n2 smoker           6.68\n```\n\n\n:::\n:::\n\n\n. . . \n\n\n::: callout-note\n## Don't forget!\n\nIn a simple linear regression with a numerical response and a binary predictor, the slope estimate is the difference in the average response between the two groups.\n:::\n## Confidence interval {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-23-1.png){width=960}\n:::\n:::\n\n\nWe are 95% confident that the true mean difference is between -0.919 and -0.301. This does not contain 0!!!\n\n## Competing claims {.smaller}\n\nAre the data sufficiently informative to tell the difference between these two possibilities?\n\n$$\n\\begin{aligned}\nH_0&: \\beta_1=0 && (\\text{no effect})\\\\\nH_0&: \\beta_1\\neq0 && (\\text{some effect})\\\\\n\\end{aligned}\n$$\n\n:::incremental\n-   $\\beta_1$ is the difference in mean response between the smoking and non-smoking group;\n-   the alternative does not specify if the effect is positive or negative;\n-   the alternative does not specify that the effect is \"large\".\n:::\n\n## Hypothesis test {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-24-1.png){width=960}\n:::\n:::\n\n\n. . .\n\nThe p-value is basically zero.\n\n## What did we learn? {.smaller}\n\n::: incremental\n-   Evidence is sufficient to reject the null: smoking during pregnancy is *associated* with a difference in birth weight;\n\n-   Is smoking *causing* birth weight to change?\n\n-   The data are observational, and there are many unmeasured factors that could bear on both `habit` and `weight`.\n\n-   Maybe there is a causal relationship, and maybe it can be teased out with data like these, but it is not so straightforward\n:::\n\n. . .\n\n> Just because there is a statistically discernible association does not mean there is a causal relationship.\n\n\n## So, when can we draw causal conclusions? {.smaller}\n\n::: incremental\n-   Best hope: run a controlled, randomized experiment:\n\n    -   get a big, representative, random sample from target population;\n    -   randomly divide subjects into treatment and control;\n    -   difference in outcomes was *caused* by the treatment alone;\n    -   but this may be too costly or unethical.\n\n-   Observational data are very challenging:\n\n    -   you couldn't control gosh darned thing;\n    -   different outcomes could be caused by confounding factors, which you may or may not have measured.\n:::\n\n\n## A proper, controlled experiment {.smaller}\n\nDoes treatment using embryonic stem cells (ESCs) help improve heart function following a heart attack?\nEach sheep in the study was randomly assigned to the ESC or control group, and the change in their hearts' pumping capacity was measured in the study.\nA positive value corresponds to increased pumping capacity, which generally suggests a stronger recovery.\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(stem_cell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{style='font-size: 0.5em'}\nRows: 18\nColumns: 3\n$ trmt   <fct> ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl,…\n$ before <dbl> 35.25, 36.50, 39.75, 39.75, 41.75, 45.00, 47.00, 52.0…\n$ after  <dbl> 29.50, 29.50, 36.25, 38.00, 37.50, 42.75, 39.00, 45.2…\n```\n\n\n:::\n:::\n\n\n## ABV {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstem_cell <- stem_cell |>\n  mutate(change = after - before)\n\nggplot(stem_cell, aes(x = change, y = trmt)) + \n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-26-1.png){width=960}\n:::\n:::\n\n\n## Model fit {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() |>\n  fit(change ~ trmt, data = stem_cell) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic p.value\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)    -4.33      1.38     -3.14 0.00639\n2 trmtesc         7.83      1.95      4.01 0.00102\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{change}=-4.33+7.83\\times \\texttt{esc}\n$$\n\n\n## Remember... {.smaller}\n\n$$\n\\widehat{change}=-4.33+7.83\\times \\texttt{esc}\n$$\n\n::: incremental\n-   `trmt` is categorical with two levels: `ctrl` (0) and `esc` (1).\n\n-   The control group has `esc = 0`, so $$\n    \\widehat{change} = -4.33;\n    $$\n\n-   The treatment group has `esc = 1`, so $$\n    \\widehat{change} = -4.33+7.83=3.5.\n    $$\n:::\n\n## Again, those were not magic numbers!! {.smaller}\n \n\n::: {.cell}\n\n```{.r .cell-code}\nstem_cell |>\n  group_by(trmt) |>\n  summarize(\n    mean_change = mean(change)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  trmt  mean_change\n  <fct>       <dbl>\n1 ctrl        -4.33\n2 esc          3.5 \n```\n\n\n:::\n:::\n\n\n\n## Confidence interval {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-29-1.png){width=960}\n:::\n:::\n\n\nWe are 95% confident that the true mean difference is between 4.34 and 11.7.\n\n## Competing claims: again! {.smaller}\n\nAre the data sufficiently informative to tell the difference between these two possibilities?\n\n$$\n\\begin{aligned}\nH_0&: \\beta_1=0 && (\\text{no effect})\\\\\nH_0&: \\beta_1\\neq0 && (\\text{some effect})\\\\\n\\end{aligned}\n$$\n\n-   $\\beta_1$ is the difference in mean response between the treatment and control group;\n-   the alternative does not specify if the effect is positive or negative;\n-   the alternative does not specify that the effect is \"large\".\n\n## Hypothesis test {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](23-inference-recap_files/figure-revealjs/unnamed-chunk-30-1.png){width=960}\n:::\n:::\n\n\n. . .\n\nThe p-value is basically zero.\n\n## What did we learn? {.smaller}\n\n::: incremental\n-   In a hypothetical world where the treatment has no effect, it would be very unlikely to get results like the ones we did;\n\n-   Evidence is sufficient to *reject the null*.\n    There is *some* effect;\n\n-   If you are convinced by the experimental design, the effect is *causal*;\n\n-   Is the effect large and meaningful and something you should base major decisions on?\n    Statistics cannot answer that question!\n:::\n\n\n## AE !",
    "supporting": [
      "23-inference-recap_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}