<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-3e476e15ae565c222d94875412ae43a1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">
<meta name="author" content="Katie Solarz">
<meta name="dcterms.date" content="2026-06-11">
<title>STA 199 – Logistic Regression II</title>
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
<link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
<link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
<style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #767676;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #767676;  padding-left: 4px; }
    div.sourceCode
      { color: #545454; background-color: #fefefe; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #545454; } /* Normal */
    code span.al { color: #7928a1; } /* Alert */
    code span.an { color: #696969; } /* Annotation */
    code span.at { color: #a55a00; } /* Attribute */
    code span.bn { color: #7928a1; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #d91e18; } /* ControlFlow */
    code span.ch { color: #008000; } /* Char */
    code span.cn { color: #d91e18; } /* Constant */
    code span.co { color: #696969; } /* Comment */
    code span.cv { color: #696969; font-style: italic; } /* CommentVar */
    code span.do { color: #696969; font-style: italic; } /* Documentation */
    code span.dt { color: #7928a1; } /* DataType */
    code span.dv { color: #7928a1; } /* DecVal */
    code span.er { color: #7928a1; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #a55a00; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #696969; } /* Information */
    code span.kw { color: #d91e18; } /* Keyword */
    code span.op { color: #00769e; } /* Operator */
    code span.ot { color: #d91e18; } /* Other */
    code span.pp { color: #7928a1; } /* Preprocessor */
    code span.sc { color: #00769e; } /* SpecialChar */
    code span.ss { color: #008000; } /* SpecialString */
    code span.st { color: #008000; } /* String */
    code span.va { color: #a55a00; } /* Variable */
    code span.vs { color: #008000; } /* VerbatimString */
    code span.wa { color: #696969; font-style: italic; } /* Warning */
  </style>
<link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-1f377f1ccadea7e9b0e26a49b7195540.css">
<link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
<style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Logistic Regression II – STA 199">
<meta property="og:description" content="Lecture 18">
<meta property="og:site_name" content="STA 199">
<meta name="twitter:title" content="Logistic Regression II – STA 199">
<meta name="twitter:description" content="Lecture 18">
<meta name="twitter:image" content="https://sta199-su26.github.io/slides/img/twitter-card-ks.pdf">
<meta name="twitter:creator" content="@minebocek">
<meta name="twitter:card" content="summary_large_image">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center"><h1 class="title">Logistic Regression II</h1>
  <p class="subtitle">Lecture 18</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Katie Solarz 
</div>
        <p class="quarto-title-affiliation">
            Duke University <br> STA 199 Summer 2026: Session I
          </p>
    </div>
</div>

  <p class="date">June 11, 2026</p>
</section><section><section id="recap" class="title-slide slide level1 center"><h1>Recap</h1>

</section><section id="last-time-regression-with-a-binary-response" class="slide level2 smaller"><h2>Last time: regression with a binary response</h2>
<p><span class="math display">\[
y =
\begin{cases}
1 &amp; &amp;&amp;\text{eg. Yes, Win, True, Heads, Success, Spam}\\
0 &amp; &amp;&amp;\text{eg. No, Lose, False, Tails, Failure, Legit}.
\end{cases}
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-1-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="new-model-logistic-regression" class="slide level2"><h2>New model: logistic regression</h2>
<p>S-curve for the probability of “success”:</p>
<p><span class="math display">\[
\widehat{p}
=
\widehat{\text{Prob}(y=1)}
=
\frac{e^{b_0+b_1x}}{1+e^{b_0+b_1x}}.
\]</span></p>
<p>Linear model for the log-odds:</p>
<p><span class="math display">\[
\log\left(\frac{\hat{p}}{1-\hat{p}}\right)
=
b_0+b_1x.
\]</span></p>
<p>These are equivalent.</p>
</section><section id="r-syntax-is-largely-unchanged" class="slide level2 small"><h2>R syntax is largely unchanged</h2>
<p>Just use <code>logistic_reg</code> instead of <code>linear_reg</code>:</p>
<div class="fragment">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>simple_logistic_fit <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a></a>  <span class="fu">fit</span>(spam <span class="sc">~</span> exclaim_mess, <span class="at">data =</span> email)</span>
<span id="cb1-3"><a></a></span>
<span id="cb1-4"><a></a><span class="fu">tidy</span>(simple_logistic_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term          estimate std.error statistic p.value
  &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)  -2.27      0.0553     -41.1     0    
2 exclaim_mess  0.000272  0.000949     0.287   0.774</code></pre>
</div>
</div>
</div>
<div class="fragment">
<p>Fitted equation for the log-odds:</p>
<p><span class="math display">\[
\log\left(\frac{\hat{p}}{1-\hat{p}}\right)
=
-2.27
+
0.000272\times exclaim~mess
\]</span></p>
</div>
</section><section id="interpretations-are-strange-and-delicate" class="slide level2 small scrollable"><h2>Interpretations are strange and delicate</h2>
<div>
<ul>
<li class="fragment"><p>If <code>exclaim_mess = 0</code>, then <span class="math display">\[
\widehat{p}=\widehat{P(y=1)}=\frac{e^{-2.27}}{1+e^{-2.27}}\approx 0.09.
\]</span> So, our model predicts that an email with no exclamation marks has a 9% probability of being spam.</p></li>
<li class="fragment"><p>If the email has an additional exclamation mark, we predict the <em>odds</em> of the email being spam to be <strong>higher</strong> by a factor of <span class="math inline">\(e^{b_1} = e^{0.000272}\approx 1.000272\)</span>, on average.</p></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>The odds are <em>higher</em> because the scale factor is greater than one. If it had been 0.98, then the odds shrink and the interpretation would change to “we predict the odds to be <strong>lower</strong> by a factor of 0.98”</p></li>
<li><p>For any slope estimate &gt; 0 (i.e., <span class="math inline">\(b_1 &gt; 0\)</span>), the multiplicative factor will be larger than 1 (use “higher” or “increase” by a factor of <span class="math inline">\(e^{b_1}\)</span>); for any slope estimate &lt; 0, the multiplicative factor will be 0 &lt; <span class="math inline">\(e^{b_1}\)</span> &lt; 1 (use “lower” or “decrease” by a factor of …); for a slope estimate of exactly 0, the multiplicative factor is <span class="math inline">\(e^0 = 1\)</span>, and so the odds remain unchanged</p></li>
</ul>
</div>
</section><section id="compute-predicted-probabilities-with-the-expit-function" class="slide level2 small scrollable"><h2>Compute predicted <em>probabilities</em> with the expit function</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">tidy</span>(simple_logistic_fit) <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"(Intercept)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a></a>  <span class="fu">summarize</span>(</span>
<span id="cb3-4"><a></a>    <span class="at">prob0 =</span> <span class="fu">exp</span>(estimate) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(estimate))</span>
<span id="cb3-5"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
   prob0
   &lt;dbl&gt;
1 0.0934</code></pre>
</div>
</div>
<ul>
<li><p>Note: When interpreting an intercept term, be mindful of which representation of the outcome the instructions / question asks for the interpretation with respect to</p></li>
<li>
<p>Ex: “Interpret the intercept with respect to the <em>probability</em> of success…”</p>
<ul>
<li>You should be using the expit function to get just <span class="math inline">\(\widehat{p}\)</span> on the LHS!</li>
</ul>
</li>
<li>
<p>If a particular outcome is not specified, you can choose which to interpret with respect to, but be sure you’re doing the right math!</p>
<ul>
<li><p>Ex: It would be <strong>incorrect</strong> to state the following here: “For an email with 0 exclamation points, we predict the odds of that email being spam to be -2.27.”</p></li>
<li><p>Why? -2.27 is the predicted <em>log-odds</em>. If you want to say something about the predicted odds, you must “un-log” your outcome i.e., compute <span class="math inline">\(e^{-2.27}\)</span></p></li>
</ul>
</li>
</ul></section><section id="print-exponentiated-estimates-to-screen" class="slide level2 medium scrollable"><h2>Print exponentiated estimates to screen</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">tidy</span>(simple_logistic_fit) <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a></a>  <span class="fu">mutate</span>(<span class="at">exp_estimate =</span> <span class="fu">exp</span>(estimate)) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a></a>  <span class="fu">select</span>(term, estimate, exp_estimate, std.error, statistic, p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  term          estimate exp_estimate std.error statistic p.value
  &lt;chr&gt;            &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)  -2.27            0.103  0.0553     -41.1     0    
2 exclaim_mess  0.000272        1.00   0.000949     0.287   0.774</code></pre>
</div>
</div>
</section><section id="heres-an-alternative-model" class="slide level2 small scrollable"><h2>Here’s an alternative model</h2>
<p>Dump all the predictors in:</p>
<blockquote>
<p>Using a <code>.</code> on the RHS of the <code>~</code> in fit() will throw all columns in the data frame you supply into the model (except for the outcome column itself) as predictors. This is a time-saver and avoids the need for listing every variable manually</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>full_logistic_fit <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a></a>  <span class="fu">fit</span>(spam <span class="sc">~</span> ., <span class="at">data =</span> email)</span>
<span id="cb7-3"><a></a></span>
<span id="cb7-4"><a></a><span class="fu">tidy</span>(full_logistic_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 22 × 5
   term         estimate std.error statistic  p.value
   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept)  -9.09e+1   9.80e+3  -0.00928 9.93e- 1
 2 to_multiple1 -2.68e+0   3.27e-1  -8.21    2.25e-16
 3 from1        -2.19e+1   9.80e+3  -0.00224 9.98e- 1
 4 cc            1.88e-2   2.20e-2   0.855   3.93e- 1
 5 sent_email1  -2.07e+1   3.87e+2  -0.0536  9.57e- 1
 6 time          8.48e-8   2.85e-8   2.98    2.92e- 3
 7 image        -1.78e+0   5.95e-1  -3.00    2.73e- 3
 8 attach        7.35e-1   1.44e-1   5.09    3.61e- 7
 9 dollar       -6.85e-2   2.64e-2  -2.59    9.64e- 3
10 winneryes     2.07e+0   3.65e-1   5.67    1.41e- 8
# ℹ 12 more rows</code></pre>
</div>
</div>
</section><section id="classification-error" class="slide level2"><h2>Classification error</h2>
<p>There are two kinds of mistakes:</p>
<p><img data-src="img/17/confusion-matrix.png"></p>
<p>We want to avoid both, but there’s a trade-off.</p>
</section><section id="jargon-false-negative-and-positive" class="slide level2 medium scrollable"><h2>Jargon: False negative and positive</h2>
<ul>
<li>
<p><strong>False negative rate (FNR)</strong> is the <em>proportion</em> of actual positives that were classified as negatives.</p>
<ul>
<li>FNR = (FN) / (FN + TP), where FN = # false negatives, TP = # true positives</li>
</ul>
</li>
<li>
<p><strong>False positive rate (FPR)</strong> is the <em>proportion</em> of actual negatives that were classified as positives.</p>
<ul>
<li>FPR = (FP) / (FP + TN), where FP = # false positives, TN = # true negatives</li>
</ul>
</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>We want these <strong>both</strong> to be low!</p>
</div>
</div>
</div>
</section><section id="jargon-sensitivity" class="slide level2"><h2>Jargon: Sensitivity</h2>
<p><strong>Sensitivity</strong> is the <em>proportion</em> of actual positives that were correctly classified as positive.</p>
<ul>
<li><p>Also known as <strong>true positive rate (TPR)</strong> and <strong>recall</strong></p></li>
<li><p>Sensitivity = 1 − false negative rate (FNR)</p></li>
<li><p>Useful when false negatives are more “expensive” than false positives</p></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>We want this to be high!</p>
</div>
</div>
</div>
</section><section id="jargon-specificity" class="slide level2"><h2>Jargon: Specificity</h2>
<p><strong>Specificity</strong> is the <em>proportion</em> of actual negatives that were correctly classified as negative</p>
<ul>
<li><p>Also known as <strong>true negative rate (TNR)</strong></p></li>
<li><p>Specificity = 1 − false positive rate (FPR)</p></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>We want this to be high!</p>
</div>
</div>
</div>
</section><section id="the-augment-function" class="slide level2"><h2>The augment function</h2>
<p>The <code>augment</code> function takes a data frame and “augments” it by adding three new columns on the left that describe the model predictions for each row:</p>
<ul>
<li>
<code>.pred_class</code>: model prediction (<span class="math inline">\(\widehat{y}\)</span>), based on a 50% threshold by default;</li>
<li>
<code>.pred_0</code>: model estimate of <span class="math inline">\(P(y=0)\)</span>;</li>
<li>
<code>.pred_1</code>: model estimate of <span class="math inline">\(P(y=1) = 1 - P(y = 0)\)</span>.</li>
</ul></section><section id="the-augment-function-1" class="slide level2 medium scrollable"><h2>The augment function</h2>
<p>The <code>augment</code> function takes a data frame and “augments” it by adding three new columns on the left that describe the model predictions for each row:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a>log_aug_full <span class="ot">&lt;-</span> <span class="fu">augment</span>(full_logistic_fit, email)</span>
<span id="cb9-2"><a></a>log_aug_full</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,921 × 24
   .pred_class .pred_0  .pred_1 spam  to_multiple from     cc
   &lt;fct&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;       &lt;fct&gt; &lt;int&gt;
 1 0             0.867 1.33e- 1 0     0           1         0
 2 0             0.943 5.70e- 2 0     0           1         0
 3 0             0.942 5.78e- 2 0     0           1         0
 4 0             0.920 7.96e- 2 0     0           1         0
 5 0             0.903 9.74e- 2 0     0           1         0
 6 0             0.901 9.87e- 2 0     0           1         0
 7 0             1.000 7.89e-12 0     1           1         0
 8 0             1.000 1.24e-12 0     1           1         1
 9 0             0.862 1.38e- 1 0     0           1         0
10 0             0.922 7.76e- 2 0     0           1         0
# ℹ 3,911 more rows
# ℹ 17 more variables: sent_email &lt;fct&gt;, time &lt;dttm&gt;, image &lt;dbl&gt;,
#   attach &lt;dbl&gt;, dollar &lt;dbl&gt;, winner &lt;fct&gt;, inherit &lt;dbl&gt;,
#   viagra &lt;dbl&gt;, password &lt;dbl&gt;, num_char &lt;dbl&gt;, line_breaks &lt;int&gt;,
#   format &lt;fct&gt;, re_subj &lt;fct&gt;, exclaim_subj &lt;dbl&gt;,
#   urgent_subj &lt;fct&gt;, exclaim_mess &lt;dbl&gt;, number &lt;fct&gt;</code></pre>
</div>
</div>
</section><section id="calculating-the-error-rates" class="slide level2"><h2>Calculating the error rates</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>log_aug_full <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a></a>  <span class="fu">count</span>(spam, .pred_class) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  spam  .pred_class     n
  &lt;fct&gt; &lt;fct&gt;       &lt;int&gt;
1 0     0            3521
2 0     1              33
3 1     0             299
4 1     1              68</code></pre>
</div>
</div>
</section><section id="calculating-the-error-rates-1" class="slide level2"><h2>Calculating the error rates</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>log_aug_full <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a></a>  <span class="fu">group_by</span>(spam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   spam [2]
  spam  .pred_class     n
  &lt;fct&gt; &lt;fct&gt;       &lt;int&gt;
1 0     0            3521
2 0     1              33
3 1     0             299
4 1     1              68</code></pre>
</div>
</div>
</section><section id="calculating-the-error-rates-2" class="slide level2"><h2>Calculating the error rates</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>log_aug_full <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb15-4"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   spam [2]
  spam  .pred_class     n       p
  &lt;fct&gt; &lt;fct&gt;       &lt;int&gt;   &lt;dbl&gt;
1 0     0            3521 0.991  
2 0     1              33 0.00929
3 1     0             299 0.815  
4 1     1              68 0.185  </code></pre>
</div>
</div>
</section><section id="calculating-the-error-rates-3" class="slide level2 scrollable"><h2>Calculating the error rates</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a>log_aug_full <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb17-4"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-5"><a></a>    <span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n),</span>
<span id="cb17-6"><a></a>    <span class="at">decision =</span> <span class="fu">case_when</span>(</span>
<span id="cb17-7"><a></a>      spam <span class="sc">==</span> <span class="st">"0"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"0"</span> <span class="sc">~</span> <span class="st">"True negative"</span>,</span>
<span id="cb17-8"><a></a>      spam <span class="sc">==</span> <span class="st">"0"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"1"</span> <span class="sc">~</span> <span class="st">"False positive"</span>,</span>
<span id="cb17-9"><a></a>      spam <span class="sc">==</span> <span class="st">"1"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"0"</span> <span class="sc">~</span> <span class="st">"False negative"</span>,</span>
<span id="cb17-10"><a></a>      spam <span class="sc">==</span> <span class="st">"1"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"1"</span> <span class="sc">~</span> <span class="st">"True positive"</span></span>
<span id="cb17-11"><a></a>    ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
# Groups:   spam [2]
  spam  .pred_class     n       p decision      
  &lt;fct&gt; &lt;fct&gt;       &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;         
1 0     0            3521 0.991   True negative 
2 0     1              33 0.00929 False positive
3 1     0             299 0.815   False negative
4 1     1              68 0.185   True positive </code></pre>
</div>
</div>
</section><section id="but-wait" class="slide level2 scrollable"><h2>But wait!</h2>
<p>If we change the classification threshold, we change the classifications, and we change the error rates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>log_aug_full <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&gt;</span> <span class="fl">0.25</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb19-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb19-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb19-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb19-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   spam [2]
  spam  .pred_class     n      p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;
1 0               0  3263 0.918 
2 0               1   291 0.0819
3 1               0   172 0.469 
4 1               1   195 0.531 </code></pre>
</div>
</div>
</section><section id="classification-threshold-0.00" class="slide level2"><h2>Classification threshold: 0.00</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>log_aug_full <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&gt;</span> <span class="fl">0.00</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb21-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb21-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb21-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb21-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
# Groups:   spam [2]
  spam  .pred_class     n     p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt;
1 0               1  3554     1
2 1               1   367     1</code></pre>
</div>
</div>
</section><section id="classification-threshold-0.25" class="slide level2"><h2>Classification threshold: 0.25</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>log_aug_full <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&gt;</span> <span class="fl">0.25</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb23-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb23-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb23-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb23-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   spam [2]
  spam  .pred_class     n      p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;
1 0               0  3263 0.918 
2 0               1   291 0.0819
3 1               0   172 0.469 
4 1               1   195 0.531 </code></pre>
</div>
</div>
</section><section id="classification-threshold-0.5" class="slide level2"><h2>Classification threshold: 0.5</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a>log_aug_full <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb25-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&gt;</span> <span class="fl">0.50</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb25-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb25-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb25-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   spam [2]
  spam  .pred_class     n       p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
1 0               0  3521 0.991  
2 0               1    33 0.00929
3 1               0   299 0.815  
4 1               1    68 0.185  </code></pre>
</div>
</div>
</section><section id="classification-threshold-0.75" class="slide level2"><h2>Classification threshold: 0.75</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb27" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a>log_aug_full <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&gt;</span> <span class="fl">0.75</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb27-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb27-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb27-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb27-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   spam [2]
  spam  .pred_class     n       p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
1 0               0  3544 0.997  
2 0               1    10 0.00281
3 1               0   339 0.924  
4 1               1    28 0.0763 </code></pre>
</div>
</div>
</section><section id="classification-threshold-1.00" class="slide level2"><h2>Classification threshold: 1.00</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb29" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>log_aug_full <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&gt;</span> <span class="fl">1.00</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb29-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb29-5"><a></a>  <span class="fu">count</span>(spam, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb29-6"><a></a>  <span class="fu">group_by</span>(spam) <span class="sc">|&gt;</span></span>
<span id="cb29-7"><a></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
# Groups:   spam [2]
  spam  .pred_class     n     p
  &lt;fct&gt;       &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt;
1 0               0  3554     1
2 1               0   367     1</code></pre>
</div>
</div>
</section><section id="lets-plot-these-error-rates" class="slide level2"><h2>Let’s plot these error rates</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-17-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="roc-curve" class="slide level2 small"><h2>ROC curve</h2>
<p>If we repeat this process for “all” possible thresholds <span class="math inline">\(0\leq p^\star\leq 1\)</span>, we trace out the <strong>receiver operating characteristic curve</strong> (ROC curve), which assesses the model’s performance across a range of thresholds:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-18-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="roc-curve-1" class="slide level2 scrollable"><h2>ROC curve</h2>
<div class="task">
<p>Which corner of the plot indicates the best model performance?</p>
</div>
<p><img data-src="img/18/roc-curve-annotated.png"></p>
<div class="fragment">
<p>Upper left!</p>
</div>
</section><section id="roc-for-full-model" class="slide level2"><h2>ROC for full model</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-19-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="roc-for-simple-model" class="slide level2"><h2>ROC for simple model</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-20-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Comparing these two curves, the full model is better.</p>
</section><section id="model-comparison" class="slide level2"><h2>Model comparison</h2>
<p>The farther up and to the left the ROC curve is, the better the classification accuracy. You can quantify this with the area under the curve.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Area under the ROC curve (“AUC”) will be our “quality score” for comparing logistic regression models, <strong>NOT</strong> adjusted <span class="math inline">\(R^2\)</span>.</p>
</div>
</div>
</div>
</section></section><section><section id="washington-forests" class="title-slide slide level1 center"><h1>Washington forests</h1>

</section><section id="data" class="slide level2 smaller"><h2>Data</h2>
<ul>
<li><p>The U.S. Forest Service maintains machine learning models to predict whether a plot of land is “forested.”</p></li>
<li><p>This classification is important for research, legislation, land management, etc. purposes.</p></li>
<li><p>Plots are typically remeasured every 10 years.</p></li>
<li><p>The <code>forested</code> dataset contains the most recent measurement per plot.</p></li>
</ul></section><section id="data-forested" class="slide level2 smaller"><h2>Data: <code>forested</code>
</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>forested</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,107 × 19
   forested  year elevation eastness northness roughness tree_no_tree
   &lt;fct&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt;       
 1 Yes       2005       881       90        43        63 Tree        
 2 Yes       2005       113      -25        96        30 Tree        
 3 No        2005       164      -84        53        13 Tree        
 4 Yes       2005       299       93        34         6 No tree     
 5 Yes       2005       806       47       -88        35 Tree        
 6 Yes       2005       736      -27       -96        53 Tree        
 7 Yes       2005       636      -48        87         3 No tree     
 8 Yes       2005       224      -65       -75         9 Tree        
 9 Yes       2005        52      -62        78        42 Tree        
10 Yes       2005      2240      -67       -74        99 No tree     
# ℹ 7,097 more rows
# ℹ 12 more variables: dew_temp &lt;dbl&gt;, precip_annual &lt;dbl&gt;,
#   temp_annual_mean &lt;dbl&gt;, temp_annual_min &lt;dbl&gt;,
#   temp_annual_max &lt;dbl&gt;, temp_january_min &lt;dbl&gt;, vapor_min &lt;dbl&gt;,
#   vapor_max &lt;dbl&gt;, canopy_cover &lt;dbl&gt;, lon &lt;dbl&gt;, lat &lt;dbl&gt;,
#   land_type &lt;fct&gt;</code></pre>
</div>
</div>
</section><section id="data-forested-1" class="slide level2 smaller"><h2>Data: <code>forested</code>
</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a><span class="fu">glimpse</span>(forested)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 7,107
Columns: 19
$ forested         &lt;fct&gt; Yes, Yes, No, Yes, Yes, Yes, Yes, Yes, Yes,…
$ year             &lt;dbl&gt; 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2…
$ elevation        &lt;dbl&gt; 881, 113, 164, 299, 806, 736, 636, 224, 52,…
$ eastness         &lt;dbl&gt; 90, -25, -84, 93, 47, -27, -48, -65, -62, -…
$ northness        &lt;dbl&gt; 43, 96, 53, 34, -88, -96, 87, -75, 78, -74,…
$ roughness        &lt;dbl&gt; 63, 30, 13, 6, 35, 53, 3, 9, 42, 99, 51, 19…
$ tree_no_tree     &lt;fct&gt; Tree, Tree, Tree, No tree, Tree, Tree, No t…
$ dew_temp         &lt;dbl&gt; 0.04, 6.40, 6.06, 4.43, 1.06, 1.35, 1.42, 6…
$ precip_annual    &lt;dbl&gt; 466, 1710, 1297, 2545, 609, 539, 702, 1195,…
$ temp_annual_mean &lt;dbl&gt; 6.42, 10.64, 10.07, 9.86, 7.72, 7.89, 7.61,…
$ temp_annual_min  &lt;dbl&gt; -8.32, 1.40, 0.19, -1.20, -5.98, -6.00, -5.…
$ temp_annual_max  &lt;dbl&gt; 12.91, 15.84, 14.42, 15.78, 13.84, 14.66, 1…
$ temp_january_min &lt;dbl&gt; -0.08, 5.44, 5.72, 3.95, 1.60, 1.12, 0.99, …
$ vapor_min        &lt;dbl&gt; 78, 34, 49, 67, 114, 67, 67, 31, 60, 79, 17…
$ vapor_max        &lt;dbl&gt; 1194, 938, 754, 1164, 1254, 1331, 1275, 944…
$ canopy_cover     &lt;dbl&gt; 50, 79, 47, 42, 59, 36, 14, 27, 82, 12, 74,…
$ lon              &lt;dbl&gt; -118.6865, -123.0825, -122.3468, -121.9144,…
$ lat              &lt;dbl&gt; 48.69537, 47.07991, 48.77132, 45.80776, 48.…
$ land_type        &lt;fct&gt; Tree, Tree, Tree, Tree, Tree, Tree, Non-tre…</code></pre>
</div>
</div>
</section><section id="data-forested-2" class="slide level2"><h2>Data: <code>forested</code>
</h2>
<div>
<ul>
<li class="fragment"><p>7107 rows and 19 columns;</p></li>
<li class="fragment"><p>Each observation (row) is a plot of land;</p></li>
<li class="fragment"><p>Variables include geographical and meteorological information about each plot, as well as a binary indicator <code>forested</code> (“Yes” or “No”);</p></li>
<li class="fragment"><p>Given information about a plot that is easy (and cheap) to collect remotely, can we use a model to predict if a plot is forested without actually visiting it (which could be difficult and costly)?</p></li>
</ul>
</div>
</section><section id="outcome-and-predictors" class="slide level2 smaller"><h2>Outcome and predictors</h2>
<ul>
<li>Outcome: <code>forested</code> - Factor, <code>Yes</code> (baseline, 0) or <code>No</code> (1)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a><span class="fu">levels</span>(forested<span class="sc">$</span>forested)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Yes" "No" </code></pre>
</div>
</div>
<ul>
<li>
<p>Predictors: 18 remotely-sensed and easily-accessible predictors:</p>
<ul>
<li><p>numeric variables based on weather and topography</p></li>
<li><p>categorical variables based on classifications from other governmental organizations</p></li>
</ul>
</li>
</ul></section><section id="forested" class="slide level2"><h2><code>?forested</code></h2>
<iframe width="900" height="500" src="https://simonpcouch.github.io/forested/reference/forested.html" title="forested" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section><section id="should-we-include-a-predictor" class="slide level2"><h2>Should we include a predictor?</h2>
<p>To determine whether we should include a predictor in a model, we should start by asking:</p>
<div>
<ul>
<li class="fragment"><p>Is it ethical to use this variable? (Or even legal?)</p></li>
<li class="fragment"><p>Will this variable be available at prediction time?</p></li>
<li class="fragment"><p>Does this variable contribute to explainability?</p></li>
</ul>
</div>
</section></section><section><section id="data-splitting-and-spending" class="title-slide slide level1 center"><h1>Data splitting and spending</h1>

</section><section id="goal" class="slide level2"><h2>Goal</h2>
<div>
<ul>
<li class="fragment"><p>Use the data we’ve already seen to predict if a yet-to-be-observed plot of land is forested;</p></li>
<li class="fragment"><p>We want a model that does well on data it has never seen before;</p></li>
<li class="fragment"><p>“Out-of-sample” predictions on new data are more useful than “in-sample” predictions on old data;</p></li>
</ul>
</div>
</section><section id="weve-been-cheating" class="slide level2"><h2>We’ve been cheating!</h2>
<div>
<ul>
<li class="fragment"><p>So far, we’ve been using all the data we have for building models. In predictive contexts, this would be considered <em>cheating</em>.</p></li>
<li class="fragment"><p>Evaluating model performance for predicting outcomes that were used when building the models is like evaluating your learning with questions whose answers you’ve already seen.</p></li>
</ul>
</div>
</section><section id="spending-your-data" class="slide level2 smaller scrollable"><h2>Spending your data</h2>
<p>For predictive models (used primarily in machine learning), we typically split data into training and test sets:</p>
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="img/18/test-train-split-1.svg" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
<ul>
<li><p>The <strong>training set</strong> is used to estimate model parameters.</p></li>
<li><p>The <strong>test set</strong> is used to find an independent assessment of model performance.</p></li>
</ul>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Do not use, or even peek at, the test set during training.</p>
</div>
</div>
</div>
</div>
</section><section id="how-much-to-spend" class="slide level2"><h2>How much to spend?</h2>
<div>
<ul>
<li class="fragment"><p>The more data we spend (use in training), the better estimates we’ll get.</p></li>
<li class="fragment"><p>Spending too much data in training prevents us from computing a good assessment of predictive performance.</p></li>
<li class="fragment"><p>Spending too much data in testing prevents us from computing a good estimate of model parameters.</p></li>
</ul>
</div>
</section><section id="the-initial-split" class="slide level2"><h2>The initial split</h2>
<p>By default it’s a 75%/25% training/test split.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a><span class="fu">set.seed</span>(<span class="dv">847</span>)</span>
<span id="cb37-2"><a></a>forested_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(forested)</span>
<span id="cb37-3"><a></a>forested_split</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;Training/Testing/Total&gt;
&lt;5330/1777/7107&gt;</code></pre>
</div>
</div>
</section><section id="setting-a-seed" class="slide level2 smaller scrollable"><h2>Setting a seed</h2>
<div class="task">
<p>What does <code><a href="https://rdrr.io/r/base/Random.html">set.seed()</a></code> do?</p>
</div>
<p>TLDR: The testing/training split is random, but we want the results to be reproducible, so we “freeze the random numbers in time” by setting a seed. If we don’t tell you exactly what seed to use on an assignment, you can pick any positive integer you want.</p>
<div>
<ul>
<li class="fragment"><p>To create that split of the data, R generates “pseudo-random” numbers: while they are made to behave like random numbers, their generation is deterministic given a “seed”.</p></li>
<li class="fragment"><p>This allows us to reproduce results by setting that seed.</p></li>
<li class="fragment"><p>Which seed you pick doesn’t matter, as long as you don’t try a bunch of seeds and pick the one that gives you the best performance.</p></li>
</ul>
</div>
</section><section id="accessing-the-data" class="slide level2"><h2>Accessing the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a>forested_train <span class="ot">&lt;-</span> <span class="fu">training</span>(forested_split)</span>
<span id="cb39-2"><a></a>forested_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(forested_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="the-training-set" class="slide level2 smaller"><h2>The training set</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a>forested_train</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,330 × 19
   forested  year elevation eastness northness roughness tree_no_tree
   &lt;fct&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt;       
 1 Yes       2017       203      -76        64        39 Tree        
 2 No        2019         0        0         0         0 No tree     
 3 No        2018       479        0         0         0 No tree     
 4 Yes       2015       681       51       -85       127 No tree     
 5 Yes       2015       909      -44       -89        42 Tree        
 6 Yes       2012       118      -14       -98         2 Tree        
 7 Yes       2019      1080       -3       -99       132 Tree        
 8 Yes       2011        36       18        98        39 Tree        
 9 Yes       2015       410      -92       -38        81 Tree        
10 No        2019       764        6        99        19 No tree     
# ℹ 5,320 more rows
# ℹ 12 more variables: dew_temp &lt;dbl&gt;, precip_annual &lt;dbl&gt;,
#   temp_annual_mean &lt;dbl&gt;, temp_annual_min &lt;dbl&gt;,
#   temp_annual_max &lt;dbl&gt;, temp_january_min &lt;dbl&gt;, vapor_min &lt;dbl&gt;,
#   vapor_max &lt;dbl&gt;, canopy_cover &lt;dbl&gt;, lon &lt;dbl&gt;, lat &lt;dbl&gt;,
#   land_type &lt;fct&gt;</code></pre>
</div>
</div>
</section><section id="the-testing-data" class="slide level2 smaller"><h2>The testing data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a></a>forested_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,777 × 19
   forested  year elevation eastness northness roughness tree_no_tree
   &lt;fct&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt;       
 1 Yes       2005       736      -27       -96        53 Tree        
 2 Yes       2005       787       66       -74        95 Tree        
 3 Yes       2005      1330       99         7       212 Tree        
 4 Yes       2005      1423       46        88       180 Tree        
 5 Yes       2005      1038      -34       -93       183 No tree     
 6 No        2014       542      -32       -94        19 No tree     
 7 No        2014       290       46       -88         7 No tree     
 8 No        2014       676      -65       -75         6 No tree     
 9 No        2014       252       99         5       104 No tree     
10 Yes       2014      1634       54        83        38 Tree        
# ℹ 1,767 more rows
# ℹ 12 more variables: dew_temp &lt;dbl&gt;, precip_annual &lt;dbl&gt;,
#   temp_annual_mean &lt;dbl&gt;, temp_annual_min &lt;dbl&gt;,
#   temp_annual_max &lt;dbl&gt;, temp_january_min &lt;dbl&gt;, vapor_min &lt;dbl&gt;,
#   vapor_max &lt;dbl&gt;, canopy_cover &lt;dbl&gt;, lon &lt;dbl&gt;, lat &lt;dbl&gt;,
#   land_type &lt;fct&gt;</code></pre>
</div>
</div>
</section></section><section><section id="exploratory-data-analysis" class="title-slide slide level1 center"><h1>Exploratory data analysis</h1>

</section><section id="initial-questions" class="slide level2 smaller"><h2>Initial questions</h2>
<ul>
<li><p>What’s the distribution of the outcome, <code>forested</code>?</p></li>
<li><p>What’s the distribution of numeric variables like <code>precip_annual</code>?</p></li>
<li><p>How does the distribution of forested differ across the categorical and numerical variables?</p></li>
</ul>
<div class="fragment">
<div class="task">
<p>Which dataset should we use for the exploration? The entire data <code>forested</code>, the training data <code>forested_train</code>, or the testing data <code>forested_test</code>?</p>
</div>
</div>
</section><section id="forested-1" class="slide level2 small"><h2><code>forested</code></h2>
<p>What’s the distribution of the outcome, <code>forested</code>?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a></a><span class="fu">ggplot</span>(forested_train, <span class="fu">aes</span>(<span class="at">x =</span> forested)) <span class="sc">+</span></span>
<span id="cb44-2"><a></a>  <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-26-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="forested-2" class="slide level2 medium"><h2><code>forested</code></h2>
<p>What’s the distribution of the outcome, <code>forested</code>?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a></a>forested_train <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a></a>  <span class="fu">count</span>(forested) <span class="sc">|&gt;</span></span>
<span id="cb45-3"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb45-4"><a></a>    <span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)</span>
<span id="cb45-5"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  forested     n     p
  &lt;fct&gt;    &lt;int&gt; &lt;dbl&gt;
1 Yes       2936 0.551
2 No        2394 0.449</code></pre>
</div>
</div>
</section><section id="precip_annual" class="slide level2 small"><h2><code>precip_annual</code></h2>
<p>What’s the distribution of <code>precip_annual</code>?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a></a><span class="fu">ggplot</span>(forested_train, <span class="fu">aes</span>(<span class="at">x =</span> precip_annual)) <span class="sc">+</span></span>
<span id="cb47-2"><a></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-28-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="forested-and-precip_annual" class="slide level2 smaller scrollable"><h2>
<code>forested</code> and <code>precip_annual</code>
</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a><span class="fu">ggplot</span>(</span>
<span id="cb48-2"><a></a>  forested_train,</span>
<span id="cb48-3"><a></a>  <span class="fu">aes</span>(<span class="at">x =</span> precip_annual, <span class="at">fill =</span> forested, <span class="at">group =</span> forested)</span>
<span id="cb48-4"><a></a>  ) <span class="sc">+</span></span>
<span id="cb48-5"><a></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">200</span>, <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb48-6"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Yes"</span> <span class="ot">=</span> <span class="st">"forestgreen"</span>, <span class="st">"No"</span> <span class="ot">=</span> <span class="st">"gold2"</span>)) <span class="sc">+</span></span>
<span id="cb48-7"><a></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-29-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="forested-and-precip_annual-1" class="slide level2 smaller scrollable"><h2>
<code>forested</code> and <code>precip_annual</code>
</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb49" data-code-line-numbers="|5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a></a><span class="fu">ggplot</span>(</span>
<span id="cb49-2"><a></a>  forested_train,</span>
<span id="cb49-3"><a></a>  <span class="fu">aes</span>(<span class="at">x =</span> precip_annual, <span class="at">fill =</span> forested, <span class="at">group =</span> forested)</span>
<span id="cb49-4"><a></a>  ) <span class="sc">+</span></span>
<span id="cb49-5"><a></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">200</span>, <span class="at">position =</span> <span class="st">"fill"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb49-6"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Yes"</span> <span class="ot">=</span> <span class="st">"forestgreen"</span>, <span class="st">"No"</span> <span class="ot">=</span> <span class="st">"gold2"</span>)) <span class="sc">+</span></span>
<span id="cb49-7"><a></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-30-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="forested-and-tree_no_tree" class="slide level2 smaller scrollable"><h2>
<code>forested</code> and <code>tree_no_tree</code>
</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a></a><span class="fu">ggplot</span>(forested_train, <span class="fu">aes</span>(<span class="at">x =</span> tree_no_tree, <span class="at">fill =</span> forested)) <span class="sc">+</span></span>
<span id="cb50-2"><a></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>, <span class="at">alpha =</span> .<span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb50-3"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Yes"</span> <span class="ot">=</span> <span class="st">"forestgreen"</span>, <span class="st">"No"</span> <span class="ot">=</span> <span class="st">"gold2"</span>)) <span class="sc">+</span></span>
<span id="cb50-4"><a></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-31-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="forested-and-lat-lon" class="slide level2 smaller scrollable"><h2>
<code>forested</code> and <code>lat</code> / <code>lon</code>
</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a><span class="fu">ggplot</span>(forested_train, <span class="fu">aes</span>(<span class="at">x =</span> lon, <span class="at">y =</span> lat, <span class="at">color =</span> forested)) <span class="sc">+</span></span>
<span id="cb51-2"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb51-3"><a></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Yes"</span> <span class="ot">=</span> <span class="st">"forestgreen"</span>, <span class="st">"No"</span> <span class="ot">=</span> <span class="st">"gold2"</span>)) <span class="sc">+</span></span>
<span id="cb51-4"><a></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-32-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="precip_annual-and-lat-lon" class="slide level2 smaller scrollable"><h2>
<code>precip_annual</code> and <code>lat</code> / <code>lon</code>
</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a></a><span class="fu">ggplot</span>(forested_train, <span class="fu">aes</span>(<span class="at">x =</span> lon, <span class="at">y =</span> lat, <span class="at">color =</span> precip_annual)) <span class="sc">+</span></span>
<span id="cb52-2"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb52-3"><a></a>  <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">"annual</span><span class="sc">\n</span><span class="st">precipitation</span><span class="sc">\n</span><span class="st">(mm × 100)"</span>) <span class="sc">+</span></span>
<span id="cb52-4"><a></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-33-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section></section><section><section id="two-warnings-about-logistic-regression" class="title-slide slide level1 center"><h1>Two warnings about logistic regression</h1>

</section><section id="fyi-the-response-variable-must-be-a-factor" class="slide level2"><h2>FYI: the response variable <em>must</em> be a factor</h2>
<p><code>forested</code> already comes as a factor, so we’re lucky:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a><span class="fu">class</span>(forested<span class="sc">$</span>forested)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "factor"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a><span class="fu">levels</span>(forested<span class="sc">$</span>forested)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Yes" "No" </code></pre>
</div>
</div>
<div class="fragment">
<p>But if it didn’t, things would not work:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a></a><span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a></a>  <span class="fu">fit</span>(<span class="fu">as.numeric</span>(forested) <span class="sc">~</span> precip_annual, <span class="at">data =</span> forested_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in `check_outcome()`:
! For a classification model, the outcome should be a
  &lt;factor&gt;, not a double vector.</code></pre>
</div>
</div>
</div>
</section><section id="fyi-the-base-level-is-treated-as-failure-0" class="slide level2 medium"><h2>FYI: the base level is treated as “failure” (0)</h2>
<p>The base level here is “Yes”, so “No” is treated as “success” (1):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a></a><span class="fu">levels</span>(forested<span class="sc">$</span>forested)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Yes" "No" </code></pre>
</div>
</div>
<div class="fragment">
<p>As a result, this code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a></a><span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb61-2"><a></a>  <span class="fu">fit</span>(forested <span class="sc">~</span> precip_annual, <span class="at">data =</span> forested_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="fragment">
<p>Corresponds to this model:</p>
<p><span class="math display">\[
\text{Prob}(
\texttt{forested = "No"}
)
=
\frac{e^{\beta_0+\beta_1 x}}{1 + e^{\beta_0+\beta_1 x}}.
\]</span></p>
</div>
<div class="fragment">
<p>This is not a problem, but it means that in order to interpret the output correctly, you need to understand how your factors are leveled.</p>
</div>
</section><section id="dont-get-burned-on-this" class="slide level2"><h2>Don’t get burned on this!</h2>
<p>There are two distinct but related things going on at the same time:</p>
<div>
<ul>
<li class="fragment">Your binary response variable is a factor with two levels. There is a first level (base) and a second level;</li>
<li class="fragment">In the context of your application, one of those levels is the “negative” or “zero” case (legit e-mail) and one is the “positive” or “one” case (spam e-mail).</li>
</ul>
</div>
<div class="fragment">
<p>Do these two things agree? If not, that isn’t an <em>error</em>, but you might make mistakes when interpreting. Be careful!</p>
</div>
</section></section><section><section id="todays-ae" class="title-slide slide level1 center"><h1>Today’s AE</h1>

</section><section id="next-steps" class="slide level2 small scrollable"><h2>Next steps</h2>
<div>
<ul>
<li class="fragment"><p>Fit models on training data</p></li>
<li class="fragment"><p>Make predictions on testing data</p></li>
<li class="fragment">
<p>Evaluate predictions on testing data:</p>
<ul>
<li class="fragment">Linear models: R-squared, adjusted R-squared, RMSE (root mean squared error), etc.</li>
<li class="fragment">Logistic models: False negative and positive rates, AUC (area under the curve), etc.</li>
</ul>
</li>
<li class="fragment"><p>Make decisions based on model predictive performance, validity across various testing/training splits (aka “cross validation”), explainability</p></li>
</ul>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>We will only learn about a subset of these in this course, but you can go further into these ideas in STA 210 or STA 221 as well as in various machine learning courses.</p>
</div>
</div>
</div>
</div>
</section><section id="ae-16-forest-classification" class="slide level2 smaller"><h2>ae-16-forest-classification</h2>
<div class="appex">
<ul>
<li><p>Go to your ae project in RStudio.</p></li>
<li><p>If you haven’t yet done so, make sure all of your changes up to this point are committed and pushed, i.e., there’s nothing left in your Git pane.</p></li>
<li><p>If you haven’t yet done so, click Pull to get today’s application exercise file: <em>ae-16-forest-classification.qmd</em>. You might be prompted to install <strong>forested</strong>, say yes.</p></li>
<li><p>Work through the application exercise in class, and render, commit, and push your edits.</p></li>
</ul>
</div>
</section></section><section><section id="logistic-wrap-up" class="title-slide slide level1 center"><h1>Logistic wrap-up</h1>

</section><section id="fitting-a-logistic-regression-model" class="slide level2"><h2>Fitting a logistic regression model</h2>
<p>Similar syntax to linear regression:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a></a>forested_precip_fit <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb62-2"><a></a>  <span class="fu">fit</span>(forested <span class="sc">~</span> precip_annual, <span class="at">data =</span> forested_train)</span>
<span id="cb62-3"><a></a></span>
<span id="cb62-4"><a></a><span class="fu">tidy</span>(forested_precip_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term          estimate std.error statistic   p.value
  &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    1.58    0.0558         28.3 1.25e-175
2 precip_annual -0.00190 0.0000599     -31.8 5.24e-222</code></pre>
</div>
</div>
<div class="fragment">
<p><span class="math display">\[
\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right)
=
1.57
-
0.0019
\times
precip.
\]</span></p>
</div>
</section><section id="three-equivalent-representations" class="slide level2 smaller scrollable"><h2>Three equivalent representations</h2>
<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 34%">
<col style="width: 19%">
<col style="width: 23%">
</colgroup>
<thead><tr class="header">
<th>Version</th>
<th>equation</th>
<th>Friendly LHS?</th>
<th>Friendly RHS?</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Probability: (0, 1)</td>
<td><span class="math display">\[\widehat{p}=\frac{e^{b_0+b_1x}}{1+e^{b_0+b_1x}}\]</span></td>
<td>✅</td>
<td>❌</td>
</tr>
<tr class="even">
<td>Odds: <span class="math inline">\((0,\,\infty)\)</span>
</td>
<td><span class="math display">\[\frac{\widehat{p}}{1-\widehat{p}}=e^{b_0+b_1x}\]</span></td>
<td>🥴</td>
<td>🥴</td>
</tr>
<tr class="odd">
<td>Log-odds: <span class="math inline">\((-\infty,\,\infty)\)</span>
</td>
<td><span class="math display">\[\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right)=b_0+b_1x\]</span></td>
<td>❌</td>
<td>✅</td>
</tr>
</tbody>
</table>
<p>Take your pick depending on what you’re trying to do.</p>
</section><section id="probability-to-log-odds" class="slide level2 small"><h2>Probability to log-odds</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-39-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<ul>
<li>
<span class="math inline">\(p = 0 \to \text{log-odds}=-\infty\)</span>;</li>
<li>
<span class="math inline">\(p = 1/2 \to \text{log-odds}=0\)</span>;</li>
<li>
<span class="math inline">\(p = 1 \to \text{log-odds}=\infty\)</span>;</li>
<li>And everything in between.</li>
</ul>
<p>The log-odds transformation takes probabilities between 0 and 1 and streeetches them out to numbers between <span class="math inline">\(-\infty\)</span> and <span class="math inline">\(\infty\)</span>, for which the linear model is appropriate.</p>
</div></div>
</section><section id="interpreting-the-intercept" class="slide level2"><h2>Interpreting the intercept</h2>
<p>If precip = 0, then…</p>
<p><span class="math display">\[
\widehat{\text{Prob}(
\texttt{forested = "No"}
\mid precip = 0)}
=
\frac{e^{1.57}}{1 + e^{1.57}}\approx 0.83
\]</span></p>
<p>So when <span class="math inline">\(precip = 0\)</span>, the model predicts that the <em>probability</em> of <code>forested = "No"</code> is about 83%.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>We didn’t interpret the intercept <span class="math inline">\(b_0=1.57\)</span> directly. We transformed it into an interpretable quantity using the <em>probability</em> version of the logsitic regression model.</p>
</div>
</div>
</div>
</section><section id="interpreting-the-slope" class="slide level2 medium scrollable"><h2>Interpreting the slope</h2>
<p>Odds at <span class="math inline">\(precip\)</span>:</p>
<p><span class="math display">\[
\frac{\widehat{p}}{1-\widehat{p}}
=
{\color{blue}{e^{1.57
-
0.0019
\times
precip}}}
\]</span></p>
<div class="fragment">
<p>Odds at <span class="math inline">\(precip + 1\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\widehat{p}}{1-\widehat{p}}
&amp;=
e^{1.57
-
0.0019
\times
(precip + 1)}
\\
&amp;=
e^{1.57
-
0.0019
\times
precip - 0.0019}
\\
&amp;=
{\color{blue}{e^{1.57
-
0.0019
\times
precip}}}
\times
\color{red}{e^{-0.0019}}
\end{aligned}
\]</span></p>
</div>
<div class="fragment">
<p>If <span class="math inline">\(precip\)</span> increases by one unit, the model predicts a <em>decrease</em> in the odds that <code>forested = "No"</code> by a multiplicative factor of <span class="math inline">\(e^{-0.0019}\approx 0.99\)</span>.</p>
</div>
</section><section id="generate-predictions-for-the-test-data" class="slide level2 small"><h2>Generate predictions for the test data</h2>
<p><em>Augment</em> the test data frame with three new columns on the left that include model predictions (classifications and probabilities) for each row:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a></a>forested_precip_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(forested_precip_fit, forested_test)</span>
<span id="cb64-2"><a></a>forested_precip_aug</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,777 × 22
   .pred_class .pred_Yes .pred_No forested  year elevation eastness
   &lt;fct&gt;           &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 No              0.366  0.634   Yes       2005       736      -27
 2 Yes             0.977  0.0227  Yes       2005       787       66
 3 Yes             0.992  0.00808 Yes       2005      1330       99
 4 Yes             0.994  0.00598 Yes       2005      1423       46
 5 Yes             0.849  0.151   Yes       2005      1038      -34
 6 No              0.261  0.739   No        2014       542      -32
 7 No              0.243  0.757   No        2014       290       46
 8 No              0.250  0.750   No        2014       676      -65
 9 No              0.280  0.720   No        2014       252       99
10 Yes             0.577  0.423   Yes       2014      1634       54
# ℹ 1,767 more rows
# ℹ 15 more variables: northness &lt;dbl&gt;, roughness &lt;dbl&gt;,
#   tree_no_tree &lt;fct&gt;, dew_temp &lt;dbl&gt;, precip_annual &lt;dbl&gt;,
#   temp_annual_mean &lt;dbl&gt;, temp_annual_min &lt;dbl&gt;,
#   temp_annual_max &lt;dbl&gt;, temp_january_min &lt;dbl&gt;, vapor_min &lt;dbl&gt;,
#   vapor_max &lt;dbl&gt;, canopy_cover &lt;dbl&gt;, lon &lt;dbl&gt;, lat &lt;dbl&gt;,
#   land_type &lt;fct&gt;</code></pre>
</div>
</div>
</section><section id="how-did-the-model-perform" class="slide level2 medium"><h2>How did the model perform?</h2>
<p>These are the four possibilities:</p>
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="img/18/forested_errs.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
<ul>
<li>Our test data have the truth in the <code>forested</code> column;</li>
<li>We can compare the predictions in <code>.pred_class</code> to the true values and see how we did.</li>
</ul></section><section id="getting-the-error-rates" class="slide level2 small"><h2>Getting the error rates</h2>
<p>Count how many predictions fell into the four bins:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a></a>forested_precip_aug <span class="sc">|&gt;</span></span>
<span id="cb66-2"><a></a>  <span class="fu">count</span>(forested, .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  forested .pred_class     n
  &lt;fct&gt;    &lt;fct&gt;       &lt;int&gt;
1 Yes      Yes           664
2 Yes      No            294
3 No       Yes           138
4 No       No            681</code></pre>
</div>
</div>
<p>Still need all the tools from before the midterm!</p>
</section><section id="getting-the-error-rates-1" class="slide level2 small"><h2>Getting the error rates</h2>
<p>Compute the error rates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a></a>forested_precip_aug <span class="sc">|&gt;</span></span>
<span id="cb68-2"><a></a>  <span class="fu">count</span>(forested, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb68-3"><a></a>  <span class="fu">group_by</span>(forested) <span class="sc">|&gt;</span></span>
<span id="cb68-4"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb68-5"><a></a>    <span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)</span>
<span id="cb68-6"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   forested [2]
  forested .pred_class     n     p
  &lt;fct&gt;    &lt;fct&gt;       &lt;int&gt; &lt;dbl&gt;
1 Yes      Yes           664 0.693
2 Yes      No            294 0.307
3 No       Yes           138 0.168
4 No       No            681 0.832</code></pre>
</div>
</div>
<p>Still need all the tools from before the midterm!</p>
</section><section id="getting-the-error-rates-2" class="slide level2 small"><h2>Getting the error rates</h2>
<p>Label the rows so we don’t go crazy:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a></a>forested_precip_aug <span class="sc">|&gt;</span></span>
<span id="cb70-2"><a></a>  <span class="fu">count</span>(forested, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb70-3"><a></a>  <span class="fu">group_by</span>(forested) <span class="sc">|&gt;</span></span>
<span id="cb70-4"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb70-5"><a></a>    <span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n),</span>
<span id="cb70-6"><a></a>    <span class="at">decision =</span> <span class="fu">case_when</span>(</span>
<span id="cb70-7"><a></a>      forested <span class="sc">==</span> <span class="st">"Yes"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"Yes"</span> <span class="sc">~</span> <span class="st">"sensitivity"</span>,</span>
<span id="cb70-8"><a></a>      forested <span class="sc">==</span> <span class="st">"Yes"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"No"</span> <span class="sc">~</span> <span class="st">"false negative"</span>,</span>
<span id="cb70-9"><a></a>      forested <span class="sc">==</span> <span class="st">"No"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"Yes"</span> <span class="sc">~</span> <span class="st">"false positive"</span>,</span>
<span id="cb70-10"><a></a>      forested <span class="sc">==</span> <span class="st">"No"</span> <span class="sc">&amp;</span> .pred_class <span class="sc">==</span> <span class="st">"No"</span> <span class="sc">~</span> <span class="st">"specificity"</span>,</span>
<span id="cb70-11"><a></a>    )</span>
<span id="cb70-12"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
# Groups:   forested [2]
  forested .pred_class     n     p decision      
  &lt;fct&gt;    &lt;fct&gt;       &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;         
1 Yes      Yes           664 0.693 sensitivity   
2 Yes      No            294 0.307 false negative
3 No       Yes           138 0.168 false positive
4 No       No            681 0.832 specificity   </code></pre>
</div>
</div>
</section><section id="fyi-error-rates-sum-to-1-within-the-levels-of-the-true-outcome" class="slide level2 smaller scrollable"><h2>FYI: error rates sum to 1 within the levels of the true outcome</h2>
<div>
<ul>
<li class="fragment">For these two, the <em>denominator</em> is the number of truly “zero” cases:
<ul>
<li class="fragment">TNR: proportion of “zero” cases correctly classified as “zero;”</li>
<li class="fragment">FPR: proportion of “zero” cases incorrectly classified as “one;”</li>
</ul>
</li>
<li class="fragment">For these two, the <em>denominator</em> is the number of truly “one” cases:
<ul>
<li class="fragment">FNR: proportion of “one” cases incorrectly classified as “zero,”</li>
<li class="fragment">TPR: proportion of “one” cases correctly classified as “one.”</li>
</ul>
</li>
</ul>
</div>
<div class="fragment">
<p>So TNR + FPR = 1 and FNR + TPR = 1.</p>
<p>That’s why we did <code>group_by(forested)</code>.</p>
</div>
</section><section id="fyi-the-default-threshold-is-50" class="slide level2 small scrollable"><h2>FYI: the default threshold is 50%</h2>
<ul>
<li><p>The model produces probabilities: <code>.pred_Yes</code> and <code>.pred_No</code>;</p></li>
<li><p>The concrete classifications in the <code>.pred_class</code> column come from applying a 50% threshold to these probabilities:</p></li>
</ul>
<p><span class="math display">\[
\widehat{\text{forested}}=
\begin{cases}
\text{No} &amp; \text{.pred_Yes} \leq 0.5\\
\text{Yes} &amp; \text{.pred_Yes} &gt; 0.5.
\end{cases}
\]</span></p>
<ul>
<li>If you want to override that default, you must do so manually.</li>
</ul></section><section id="change-threshold-to-0.75" class="slide level2 smaller"><h2>Change threshold to 0.75</h2>
<p>New threshold <span class="math inline">\(\rightarrow\)</span> New classifications <span class="math inline">\(\rightarrow\)</span> New error rates</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72" data-code-line-numbers="2-4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a></a>forested_precip_aug <span class="sc">|&gt;</span></span>
<span id="cb72-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb72-3"><a></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_Yes <span class="sc">&gt;</span> <span class="fl">0.75</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)</span>
<span id="cb72-4"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb72-5"><a></a>  <span class="fu">count</span>(forested, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb72-6"><a></a>  <span class="fu">group_by</span>(forested) <span class="sc">|&gt;</span></span>
<span id="cb72-7"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb72-8"><a></a>    <span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n),</span>
<span id="cb72-9"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   forested [2]
  forested .pred_class     n      p
  &lt;fct&gt;    &lt;chr&gt;       &lt;int&gt;  &lt;dbl&gt;
1 Yes      No            489 0.510 
2 Yes      Yes           469 0.490 
3 No       No            760 0.928 
4 No       Yes            59 0.0720</code></pre>
</div>
</div>
</section><section id="unpacking-roc_curve" class="slide level2 smaller scrollable"><h2>Unpacking <code>roc_curve</code>
</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Recall the <em>augmented</em> data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a></a>forested_precip_aug <span class="sc">|&gt;</span></span>
<span id="cb74-2"><a></a>  <span class="fu">select</span>(.pred_class<span class="sc">:</span>forested)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,777 × 4
   .pred_class .pred_Yes .pred_No forested
   &lt;fct&gt;           &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt;   
 1 No              0.366  0.634   Yes     
 2 Yes             0.977  0.0227  Yes     
 3 Yes             0.992  0.00808 Yes     
 4 Yes             0.994  0.00598 Yes     
 5 Yes             0.849  0.151   Yes     
 6 No              0.261  0.739   No      
 7 No              0.243  0.757   No      
 8 No              0.250  0.750   No      
 9 No              0.280  0.720   No      
10 Yes             0.577  0.423   Yes     
# ℹ 1,767 more rows</code></pre>
</div>
</div>
<p>Recall how <code>forested</code> is leveled:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a></a><span class="fu">levels</span>(forested_precip_aug<span class="sc">$</span>forested)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Yes" "No" </code></pre>
</div>
</div>
</div><div class="column fragment" style="width:40%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a></a><span class="fu">roc_curve</span>(forested_precip_aug, </span>
<span id="cb78-2"><a></a>          <span class="at">truth =</span> forested, </span>
<span id="cb78-3"><a></a>          .pred_Yes, </span>
<span id="cb78-4"><a></a>          <span class="at">event_level =</span> <span class="st">"first"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div>
<ol type="1">
<li class="fragment">Supply <em>augmented</em> data frame;</li>
<li class="fragment">Tell it which column contains <em>true</em> classifications;</li>
<li class="fragment">Tell it which column contains the predicted probabilities for the level you care about</li>
<li class="fragment">Tell it which level of <code>truth</code> is the one you care about</li>
</ol>
</div>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Those last two arguments need to match!</p>
</div>
</div>
</div>
</div>
</div></div>
</section><section id="the-roc-curve" class="slide level2 smaller scrollable"><h2>The ROC curve</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a></a>forested_precip_roc <span class="ot">&lt;-</span> <span class="fu">roc_curve</span>(forested_precip_aug, </span>
<span id="cb79-2"><a></a>                                 <span class="at">truth =</span> forested, </span>
<span id="cb79-3"><a></a>                                 .pred_Yes, </span>
<span id="cb79-4"><a></a>                                 <span class="at">event_level =</span> <span class="st">"first"</span>)</span>
<span id="cb79-5"><a></a></span>
<span id="cb79-6"><a></a><span class="fu">ggplot</span>(forested_precip_roc, <span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span> <span class="sc">-</span> specificity, <span class="at">y =</span> sensitivity)) <span class="sc">+</span></span>
<span id="cb79-7"><a></a>  <span class="fu">geom_path</span>() <span class="sc">+</span></span>
<span id="cb79-8"><a></a>  <span class="fu">geom_abline</span>(<span class="at">lty =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb79-9"><a></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span> </span>
<span id="cb79-10"><a></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-48-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="the-roc-curve-1" class="slide level2"><h2>The ROC curve</h2>
<div>
<ul>
<li class="fragment"><p>ROC stands for receiver operating characteristic;</p></li>
<li class="fragment"><p>This visualizes the classification accuracy across a range of thresholds;</p></li>
<li class="fragment"><p>The more “up and to the left” it is, the better.</p></li>
<li class="fragment"><p>We can quantify “up and to the left” with the area under the curve (AUC).</p></li>
</ul>
</div>
</section><section id="the-roc-curve-2" class="slide level2"><h2>The ROC curve</h2>
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="img/18/roc-curve-annotated.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</section><section id="auc-1" class="slide level2"><h2>AUC = 1</h2>
<p>This is the best we could possibly do:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-49-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="auc-1-2" class="slide level2"><h2>AUC = 1 / 2</h2>
<p>Don’t waste time fitting a model. Just flip a coin:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-50-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="auc-0" class="slide level2"><h2>AUC = 0</h2>
<p>This is the worst we could possibly do:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="18-logistic-regression-2_files/figure-revealjs/unnamed-chunk-51-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section><section id="auc-for-the-model-we-fit" class="slide level2"><h2>AUC for the model we fit</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a></a><span class="fu">roc_auc</span>(</span>
<span id="cb80-2"><a></a>  forested_precip_aug, </span>
<span id="cb80-3"><a></a>  <span class="at">truth =</span> forested, </span>
<span id="cb80-4"><a></a>  .pred_Yes, </span>
<span id="cb80-5"><a></a>  <span class="at">event_level =</span> <span class="st">"first"</span></span>
<span id="cb80-6"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc binary         0.880</code></pre>
</div>
</div>
<p>Not bad!</p>
</section><section id="the-area-under-the-roc-curve" class="slide level2"><h2>The area under the ROC curve</h2>
<div>
<ul>
<li class="fragment"><p>This is a “quality score” for a logistic regression model;</p></li>
<li class="fragment"><p>When you compute it for a test data set that you set aside, the AUC is a measure of <em>out-of-sample</em> prediction accuracy;</p></li>
<li class="fragment"><p>AUC is a number between 0 and 1, where 0 is awful and 1 is great, similar to <span class="math inline">\(R^2\)</span> for linear regression.</p></li>
<li class="fragment"><p>The function <code>roc_auc</code> computes it for you, and it takes the same set of arguments as <code>roc_curve</code>.</p></li>
</ul>
</div>
</section><section id="new-commands" class="slide level2"><h2>New commands</h2>
<ul>
<li><code>logistic_reg</code></li>
<li><code>augment</code></li>
<li><code>roc_curve</code></li>
<li><code>roc_auc</code></li>
<li><code>set.seed</code></li>
<li>
<code>initial_split</code>, <code>training</code>, <code>test</code>
</li>
<li><code>geom_path</code></li>
</ul>


</section></section>
</div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="img/pfp.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://sta199-su26.github.io/">🔗 sta199-su26.github.io</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="../site_libs/revealjs/dist/reveal.js"></script><!-- reveal.js plugins --><script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script><script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script><script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script><script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script><script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script><script src="../site_libs/revealjs/plugin/notes/notes.js"></script><script src="../site_libs/revealjs/plugin/search/search.js"></script><script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script><script src="../site_libs/revealjs/plugin/math/math.js"></script><script>window.define = window.backupDefine; window.backupDefine = undefined;</script><script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script><script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script><script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp("https:\/\/sta199-su26\.github\.io\/");
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>


</body></html>