---
title: "Write-up and presentation"
subtitle: "Milestone 5"
categories: "Project"
execute:
  echo: false
  eval: true
---

# Write-up

## Expectations

Your written report must be completed in the `index.qmd` file and must be reproducible.
All team members should contribute to the GitHub repository, with regular meaningful commits.

Before you finalize your write up, make sure the printing of code chunks is off with the option `echo: false` in the YAML.

The mandatory components of the report are below.
You are free to add additional sections as necessary.
The report, including visualizations, should be no more than 10 pages long (if it were to be printed). There is no minimum page requirement; however, you should comprehensively address all components of your analysis in the report.

To check how many pages your report is, open it in your browser and go to File \> Print \> Save as PDF and review the number of pages.

Be selective in what you include in your final write-up.
The goal is to write a cohesive narrative that demonstrates a thorough and comprehensive analysis rather than to explain every step of the analysis.

You are welcome to include an appendix with additional work at the end of the written report document; however, grading will largely be based on the content in the main body of the report.
You should assume the reader will ***not*** see the material in the appendix unless prompted to view it in the main body of the report.
The appendix should be neatly formatted and easy for the reader to navigate.
It is **not** included in the 10-page limit.

## Components

### Introduction

This section includes an introduction to the project motivation and research question.

**Grading criteria:** The research question, motivation, and real-world implications of the project are clearly stated in the introduction, including citations for the data source (please include a hyperlink / clickable link to the data source) and any external research referenced.

### Data

This section includes a description of the data.
Describe the data and definitions of key variables.
Also include a description of any data cleaning steps you took to prepare the data for analysis. References to / discussion of key variables should be "human readable" (i.e., if you are discussing a variable that captures the height of female study participants stored in your data frame as `female_height_in`, you should not be referring to this "computer readable" variable name; rather, you should state something to the effect of "one variable of interest is the height of females, recorded in in,..."). 
You may also include some exploratory data analysis in this section if you wish, particularly if you took the "statistical modeling" avenue and the bulk of your analysis deals with model fitting and interpretation (and, potentially, subsequent inference). 

**Grading criteria:** The data are clearly described, including a description about how the data were originally collected and a concise definition of the variables relevant to understanding the report.
The data cleaning process is clearly described, including any decisions made in the process (e.g., creating new variables, removing observations, etc.) The exploratory data analysis helps the reader better understand the observations in the data along with interesting and relevant relationships between the variables.

### Analysis

This is where you will present the bulk of your analysis, discuss your findings, and describe key results.
The goal is not to interpret every single element of a visualization or output shown, but instead to address the research question(s), referencing key takeaways from each visualization that support your conclusions.
Focus on the variables that help you answer the research question and that provide relevant context for the reader. For those teams taking the "data science" pathway, the required animated visualization should be linked and subsequently described / interpreted. This will require saving your animation as a ".gif" file somewhere in your repo and then including a hyperlink / clickable link to this file's URL in your analysis section. For those teams taking the "statistical modeling" pathway, if the primary model is a linear regression model (simple or multivariate), regression diagnostics must be comprehensively assessed in this section. Any statistical inference (interval estimation, hypothesis testing, etc.) must be appropriately motivated (i.e., do not reference a $p$-value without formally stated hypotheses).

**Grading criteria:** The analysis steps are appropriate for the data and research question.
A thorough and careful approach is used to determine analysis types, and any concerns over appropriateness of analyses chosen are addressed.
The analysis results are clearly assessed and interesting findings from the analysis are described.
Interpretations are used to to support the key findings and conclusions, rather than merely listing, e.g., the interpretation of every summary statistic.

### Discussion

In this section you'll include a summary of what you have learned about your research question along with statistical arguments supporting your conclusions. You should reference your initial hypothesis / hypotheses with respect to your research question(s) and discuss whether the results agree / disagree.
In addition, discuss the limitations of your analysis and provide suggestions on ways the analysis could be improved.
Any potential issues pertaining to the reliability and validity of your data and appropriateness of the statistical analysis should also be discussed here.
Lastly, you might choose to include ideas for future work, but do this only if you have realistic ideas that are relevant to your project.

**Grading criteria:** Overall conclusions from analysis are clearly described, and the analysis results are put into the larger context of the subject matter and original research question.
There is thoughtful consideration of potential limitations of the data and/or analysis.
If ideas for future work are described, these are realistic and relevant to the project.

### Organization + formatting

This is an assessment of the overall presentation and formatting of the written report.

**Grading criteria:** The report neatly written and organized with clear section headers and appropriately sized figures with informative labels.
Numerical results are displayed with a reasonable number of digits, and all visualizations are neatly formatted.
All citations and links are properly formatted.
If there is an appendix, it is reasonably organized and easy for the reader to find relevant information.
All code, warnings, and messages are suppressed.
The main body of the written report (not including the appendix) is no longer than 10 pages.

### Code style + smell

This is an assessment of the overall presentation and formatting of the written report.

**Grading criteria:** The report neatly written and organized with clear section headers and appropriately sized figures with informative labels.
Numerical results are displayed with a reasonable number of digits, and all visualizations are neatly formatted.
All citations and links are properly formatted.
If there is an appendix, it is reasonably organized and easy for the reader to find relevant information.
All code, warnings, and messages are suppressed.
The main body of the written report (not including the appendix) is no longer than 10 pages.

## Grading

The write-up is due on Monday, June 22 at 9:30 am.

It is worth 35 points, broken down as follows:

| Total                         | 35 pts |
|-------------------------------|--------|
| **Introduction/Data**         | 5 pts  |
| **Analysis**                  | 15 pts |
| **Discussion**                | 5 pts  |
| **Organization + formatting** | 5 pts  |
| **Code style + smell**        | 5 pts  |

# Presentation + slides {#presentation-slides}

## Slides

In addition to the written report, your team will also create presentation slides and deliver a presentation that summarize and showcase your project.
Introduce your research question and data set, showcase visualizations, and discuss the primary conclusions.
These slides should serve as a brief visual addition to your written report and will be graded for content and quality.

You can create your slides with any software you like (Keynote, PowerPoint, Google Slides, etc.).
We recommend choosing an option that's easy to collaborate with, e.g., Google Slides.
If you choose this option, save the slides as PDF and **upload it to your repo as `presentation.pdf`.**

You can also use Quarto to make your slides!
While we won't be covering making slides with Quarto in the class, we would be happy to help you with it in office hours.
It's no different than writing other documents with Quarto, so the learning curve will not be steep!

The slide deck should be roughly 6 content slides + 1 title slide.
Here is a *suggested* outline as you think through the slides; you [**do not**]{.underline} have to use this exact format for the 6 slides.

-   Title Slide
-   Slide 1: Introduce the topic and motivation
-   Slide 2: Introduce the data
-   Slide 3-5: Highlights from EDA
-   Slide 6: Conclusions + discussion + critique

## Presentation

Presentations will be in person during lecture on Monday June 22. We will kick-off with presentations, so please ensure your slide deck is uploaded into your repo as `presentation.pdf` by 9:30am Monday morning to facilitate a smooth process. 
**The presentation should be between 5-7 minutes; there will be 2 minutes or so reserved for Q&A following each presentation.**

## Grading

The presentation is worth 25 points, broken down as follows:

| Total            | 25 pts |
|------------------|--------|
| **Slides**       | 10 pts |
| **Presentation** | 15 pts |

### Slides

Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

### Presentation

-   Time management: Did the team divide the time well among themselves or got cut off going over time?
-   Professionalism: How well did the team present? Does the presentation appear to be well practiced? Did everyone get a chance to say something meaningful about the project?
-   Teamwork: Did the team present a unified story, or did it seem like independent pieces of work patched together?
-   Creativity and critical thought: Is the project carefully thought out? Does it appear that time and effort went into the planning and implementation of the project?
-   Content: Including, but not limited to the following:
    -   Is the question well articulated in the presentation?
    -   Can the question be answered with the data?
    -   Does the analysis answer the question?
    -   Are the conclusion(s) made based on the analysis justifiable?
    -   Are the limitations carefully considered and articulated?

### Presentation order

Teams will present in alphabetical order of team names (treating the team name as a singular string by removing `_` and / or `-` characters). 
