---
title: "AE 00: Make a GitHub"
editor: 
  markdown: 
    wrap: sentence
---

## Introduction

Normally, these AEs will contain coding practice to be done alongside the instructor in lecture.
However, before you'll be able to start coding, you will need to make a GitHub account.

In tomorrow's lab & lecture (and throughout the remainder of this course), you will learn more about how GitHub works.
For now, understand that ***GitHub is like the Google Drive of coding.*** You can upload files, track changes over time, and work with others without overwriting each other's work.

In this class, we have a **GitHub organization** so that:

-   Everyone has a central place to both access and work on course materials (AEs, labs, project repos, etc.)

-   We can see your progress, provide help, and review changes over time

-   You gain familiarity with tools that are standard in data science, research, and industry

If you've never coded before, it might not be clear why we need something specialized and can't just use a Google Drive (or Box, or iCloud, or similar).
I think that this becomes more clear as you dive into coding, but the long story *very* short is that you aren't typing code into a word document.
You're using and running special code files, and normal drives are not properly equipped to handle these file types.

## Create a GitHub account

Tomorrow, we will give a more detailed introduction to using GitHub.
In order for you to access the course organization, you need an account, and we need to add your username to the list of users with access.

Go to <https://github.com/> and walk through the steps for creating an account.
I recommend using a personal email address so that your GitHub account stays with you long after your time at Duke.

::: callout-note
You'll need to choose a user name.
I recommend reviewing the user name advice at <https://happygitwithr.com/github-acct#username-advice> before choosing a username.
:::

::: {.callout-important collapse="true"}
## What if I already have a GitHub account?

If you already have a GitHub account, you do not need to create a new one for this course.
Just log in to that account to make sure you still remember your username and password.
If you are unsure of your login credentials, carefully follow GitHub's instructions for recovering this information.
If you accumulate too many failed login attempts, you will be locked out of your account for the day.
:::

## Share the Account with Us

So that we can add you to the course organization, share your username with me before you leave the classroom!
