---
title: "Final Study Guide Solutions"
format: html
---

# Concepts and main ideas

1.  Rapid-fire:

    i.  The line is chosen to make the sum of *squared* residuals as small as possible;
    ii. It measures the strength and direction of the linear association between two numerical variables;
    iii. It measures the proportion of the variation in the response variable explained by the model;
    iv.  $Y=\beta_0+\beta_1 X + \varepsilon$ is the "true," population relationship between $X$ and $Y$. $\hat{Y}=b_0+b_1 X$ is the estimated relationship based on a sample of imperfect data;
    v. If it makes sense for the predictor to take on a value of zero, and if the model prediction at zero is a value that the response could plausibly take, then the intercept is meaningful;
    vi. The computer creates two dummy variables indicating whether or not an observation belongs to the two levels of the categorical predictor that are not the base level. Then it runs a multiple linear regression with those two dummies as predictors;
    vii. A formula goes in the blank. This is `R` syntax like `y ~ x + z` where you tell the computer which columns in your data frame you want to use, and how to use them. Predictors go on the righthand side of the tilde, and the response variable goes on the left;
    viii. $\widehat{y}^{(\text{new})} = \widehat{y}^{(\text{old})} + b_1$;
    ix.  $\widehat{o}^{(\text{new})}=\widehat{o}^{(\text{old})}\times e^{b_1}$;
    x. Unadjusted $R^2$ always goes up when you add any new variable to a linear regression model, even if that variable is worthless. Unadjusted $R^2$ penalizes the addition of irrelevant predictors.

# Visual understanding

## Question 2

::: {.center-table}
| feature | quantity | 
|---------|---------|
| I | k |
| II | c |
| III |  d |
| IV |  f |
| V |  a |
| VI |  g | 
| VII |  b |
| VIII |  b |
| IX |  b |
:::

## Questions 3 - 8

3.  

    c.  This is the plain vanilla one.

4.  

    e.  Like an additive linear regression, the inclusion of the categorical predictor (with two levels) means that each level gets its own curve.

5.  

    f.  Negative slope means the probability goes down as $x$ increases.

6.  

    d.  The negative intercept makes the probability at $x=0$ tiny, so the curve shifts right.

7.  

    a.  The bigger slope means the probability increases faster as $x$ increases, so steep curve.

8.  

    b.  The itty bitty slope means the probability increases slower as $x$ increases, so flatter curve.

## Questions 9 - 12

9.  c
10. a
11. d
12. b

# Stat doctor

13. Causal-sounding language that makes the prediction sound like a guarantee.
14. A one unit (which is measured in thousands of characters here) increase in the predictor is associated with a decrease by -0.0621 in the estimated *log-odds*, not the probability.
15. Holding bill length constant, a one unit increase in flipper length is associated with a 48.14 gram *increase* in body mass, on average.
16. 1.74 is not the slope between flipper length and body mass for Chinstrap penguins. It's the *adjustment* that must be made to the baseline slope of 32.8 in order to get the Chinstrap slope. Those interaction terms are slope adjusters, not slopes themselves.
17. $R^2$ is percent of variation in the *response* that is explained by the model. `mpg` is the predictor here (since it's to the right of the tilde).
18. $e^{-2.218}\approx 0.10886$ is the *odds* of the email being spam. The probability would be

$$
\frac{e^{-2.218}}{1+e^{-2.218}}\approx 0.098.
$$

19. The base level is female, not male, so the intercept applies to the female penguins.
20. Correlation applies to *pairs* of numerical variables. We don't talk about correlation between three variables. Since this is multiple linear regression instead of simple, we cannot interpret the $R^2$ as literally the square of a correlation coefficient.

## Pokémon

21. First, they got the variables flipped. 69.66 is a prediction for *speed* when *defense* is zero. Second, our models deliver predictions, not guarantees. A defense of 0 is not guaranteed to yield a speed of 69.66. That's just the prediction *on average*.
22. Holding attack and defense constant, a one unit increase in `hp` predicts an increase in the *odds* of being legendary by a multiplicative factor of $e^{0.0274}\approx 1.027$, on average.
23. This is just nonsense. 0.85 is the area under the ROC curve for a logistic regression model. It is not the $R^2$ for a linear regression.
24. 90% (not 95%) of the *bootstrap estimates* lie between -0.065 and 0.046, not the data values themselves.
25. The p-value **is not** the probability that the null is true. It is the probability of an estimate as or more extreme than the one you observed *assuming* the null is true.
26. A discernibility level of 50% is just crazy. You would never do that. Even if you did, the conclusion is worded strangely. We don't *reject* the alternative hypothesis. You fail to reject the null. A large p-value is saying "the jury's out." The data are not speaking loudly enough to distinguish competing claims. So you aren't coming down firmly on either side if the p-value is large.

# Data analysis

## Blizzard salaries

27. \(c\) For every additional \$1,000 of annual salary, the model predicts the raise to be higher, on average, by 0.0155%.
28. \(d\) $R^2$ of `raise_2_fit` is higher than $R^2$ of `raise_1_fit` since `raise_2_fit` has one more predictor
29. The reference level of `performance_rating` is High, since it’s the first level alphabetically. Therefore, the coefficient -2.40% is the predicted difference in raise comparing High to Successful. In this context a negative coefficient makes sense since we would expect those with High performance rating to get higher raises than those with Successful performance.
30. \(a\) “Poor”, “Successful”, “High”, “Top”.
31. \(c\) Option 3. It's a linear model with no interaction effect, so parallel lines. And since the slope for `salary_typeSalaried` is positive, its intercept is higher. The equations of the lines are as follows:
    -   Hourly: $$
        \begin{align*}
        \widehat{percent\_incr} &= 1.24 + 0.0000137 \times annual\_salary + 0.913 \times salary\_typeSalaried \\
        &= 1.24 + 0.0000137 \times annual\_salary + 0.913 \times 0 \\
        &= 1.24 + 0.0000137 \times annual\_salary
        \end{align*}
        $$

    -   Salaried: $$
        \begin{align*}
        \widehat{percent\_incr} &= 1.24 + 0.0000137 \times annual\_salary + 0.913 \times salary\_typeSalaried \\
        &= 1.24 + 0.0000137 \times annual\_salary + 0.913 \times 1 \\
        &= 2.153 + 0.0000137 \times annual\_salary
        \end{align*}
        $$
32. \(c\) The model predicts that the percentage increase employees with Successful performance get, on average, is higher by a factor of 1025 compared to the employees with Poor performance rating.

## Movies

33. \(d\) `as.numeric(str_remove(runtime, " mins"))`
34. \(e\) Blue City $>$ Rang De Basanti $>$ Winter Sleep
35. \(b\) 31% of the variability in movie scores is explained by their runtime.
36. \(a\) summarize
37. \(b\) A value between 0 and 0.434.
38. \(e\) G-rated movies that are 0 minutes in length are predicted to score, on average, 4.525 points.
39. \(c\) All else held constant, for each additional minute of runtime, movie scores will be higher by 0.021 points on average.
40. \(c\) is greater than
41. \(a\) $\widehat{score} = (4.525 - 0.257) + 0.021 \times runtime$

## Holiday movies

42. c, e
43. a, b, c
44. a, b
45. e
46. a
47. e
