{
  "hash": "6f78a63d1310e3d01671a4accd6b6aaf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AE 12: Modelling penguins\"\nsubtitle: \"Suggested answers\"\n---\n\nIn this application exercise we will be studying penguins.\nThe data can be found in the **palmerpenguins** package and we will use **tidyverse** and **tidymodels** for data exploration and modeling, respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(palmerpenguins)\n```\n:::\n\n\nYou've seen the `penguins` data far too much at this point (sorry!!!), but we're going to bring it back one more time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel…\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse…\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, …\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, …\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186…\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, …\n$ sex               <fct> male, female, female, NA, female, male, female, male…\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…\n```\n\n\n:::\n:::\n\n\n# Part 1\n\nOur goal is to understand better **how various body measurements and attributes of penguins relate to their body mass**.\nFirst, we are going to investigate the relationship between a penguins' flipper lengths and their body masses.\n\n-   *Based on our research focus, body mass is the response variable.*\n\n**Task 1 - Exploratory Data Analysis:** Visualize the relationship between flipper length and body mass of penguins.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +\n  geom_point()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-12-github-A_files/figure-html/plot-bm-fl-1.png){width=672}\n:::\n:::\n\n\n## Correlation\n\n**Task 2 - Complete the following**\n\n-   **Question:** What is correlation?\n    What values can correlation take?\n\n    *Strength and direction of a linear relationship. It's bounded by -1 and 1.*\n\n    ::: callout-note\n    *Are you good at guessing correlation?* [Give it a try](https://www.guessthecorrelation.com) with this game!\n    :::\n\n-   **Code:** What is the correlation between flipper length and body mass of penguins?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# option 1\npenguins |>\n  summarize(r = cor(flipper_length_mm, body_mass_g, use = \"complete.obs\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n      r\n  <dbl>\n1 0.871\n```\n\n\n:::\n\n```{.r .cell-code}\n# option 2\npenguins |>\n  drop_na(flipper_length_mm, body_mass_g) |>\n  summarize(r = cor(flipper_length_mm, body_mass_g))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n      r\n  <dbl>\n1 0.871\n```\n\n\n:::\n:::\n\n\n## Defining, fitting, and summarizing a model\n\n**Task 3 (Demo) :** Write the [*population model*]{.underline} (model for the *true values)* below that explains the relationship between body mass and flipper length.\n\n$$\n{body mass} = \\beta_0 + \\beta_1 \\times flipper length + \\epsilon\n$$**Task 4:** Fit the linear regression model and display the results.\n[*Write the estimated model output below!*]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm, data = penguins)\n\ntidy(bm_fl_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term              estimate std.error statistic   p.value\n  <chr>                <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)        -5781.     306.       -18.9 5.59e- 55\n2 flipper_length_mm     49.7      1.52      32.7 4.37e-107\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{body mass} = -5780 + 49.7 \\times flipper length \n$$\n\n**Task 5:** Interpret the slope and the intercept in the context of the data.\n\n-   *Intercept*: Penguins with 0 flipper length are expected, on average, to weigh -5,781 grams.\n\n-   *Slope*: For each additional millimeter of a penguin;s flipper length, the weight of their penguin is expected to be higher, on average, by 49.7 grams.\n\n**Task 6:** Recreate the visualization from above, this time adding a regression line to the visualization `geom_smooth(method = \"lm\")`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  penguins,\n  aes(x = flipper_length_mm, y = body_mass_g)\n  ) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-12-github-A_files/figure-html/plot-bm-fl-line-1.png){width=672}\n:::\n:::\n\n\n**Task 7 (Demo):** What is the estimated body mass for a penguin with a flipper length of 210?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguin_flipper_210 <- tibble(flipper_length_mm = 210)\n\nbm_fl_fit |>\n  predict(new_data = penguin_flipper_210)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 4653.\n```\n\n\n:::\n:::\n\n\n**Task 8:** What is the estimated body mass for a penguin with a flipper length of 100?\nAdd code to find it!\nIs there anything weird about making this prediction?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguin_flipper_100 <- tibble(flipper_length_mm = 100)\n\nbm_fl_fit |>\n  predict(new_data = penguin_flipper_100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 -812.\n```\n\n\n:::\n:::\n\n\nWe are extrapolating when we take flipper length = 100: it is outside of the data range.\n\n# Part 2: Another model\n\n**Task 9:** A different researcher wants to look at body weight of penguins based on the island they were recorded on.\n\n-   **Question:** How are the variables involved in this analysis different?\n\n    The predictor variable is categorical, not quantitative!\n\n-   **Code:** Make an appropriate visualization to investigate this relationship below.\n    Additionally, calculate the mean body mass by island.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  ggplot(aes(x = island, y = body_mass_g)) +\n  geom_boxplot()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-12-github-A_files/figure-html/plot-bm-island-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  group_by(island) |>\n  summarize(mean_bm = mean(body_mass_g, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  island    mean_bm\n  <fct>       <dbl>\n1 Biscoe      4716.\n2 Dream       3713.\n3 Torgersen   3706.\n```\n\n\n:::\n:::\n\n\n**Task 10:** Change the geom of your previous plot to `geom_point()`.\nUse this plot to think about how R models these data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  ggplot(aes(x = island, y = body_mass_g)) +\n  geom_point()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-12-github-A_files/figure-html/plot-bm-island-points-1.png){width=672}\n:::\n:::\n\n\n**Task 11:** Fit the linear regression model and display the results.\nWrite the estimated model output below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_island_fit <- linear_reg() |>\n  fit(body_mass_g ~ island, data = penguins)\n\ntidy(bm_island_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term            estimate std.error statistic   p.value\n  <chr>              <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)        4716.      48.5      97.3 8.93e-250\n2 islandDream       -1003.      74.2     -13.5 1.42e- 33\n3 islandTorgersen   -1010.     100.      -10.1 4.66e- 21\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{bodymass} = 4716 -1003 \\times dream -1010 \\times torgersen\n$$\n\n## Interpreting Categorical Predictors\n\n**Task 12:** Fill in the blanks.\n\n-   The baseline island is Biscoe.\n-   Intercept: Penguins from Biscoe island are expected to weigh, on average, 4716 grams.\n-   Slopes:\n    -   Penguins from Dream are expected to weigh, on average, 1003 grams less than those from Biscoe.\n\n    -   Penguins from Torgersen island are expected to weigh, on average, 1010 grams less than those from Biscoe.\n\n**Task 13:** What is the estimated body weight of a penguin on Biscoe island?\nWhat are the estimated body weights of penguins on Dream and Torgersen islands?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthree_penguins <- tibble(\n  island = c(\"Biscoe\", \"Dream\", \"Torgersen\")\n)\n\nbm_island_fit |>\n  predict(new_data = three_penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 1\n  .pred\n  <dbl>\n1 4716.\n2 3713.\n3 3706.\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "ae-12-github-A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}