{
  "hash": "5e47d2a5a27899276e72acfef8a87b2f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Quantifying uncertainty with bootstrap intervals\"\nsubtitle: \"Lecture 20\"\ndate: \"2025-6-12\"\nformat: \n  revealjs:\n    output-file: 20-bootstrap-slides.html\n    pdf-separate-fragments: true\nauto-stretch: false\n---\n\n## Announcements {.smaller}\n\nProject timeline and progress:\n\n::: incremental\n-   **Due TONIGHT: Milestone 3**\n    -   Address and close issues (let me know if you are having trouble closing!)\n    -   At least one plot\n    -   All team members commit\n-   **Before Monday - Between Milestones 3 and 4**\n    -   Make real progress on your project write-up: introduction and exploratory data analysis; brainstorm of methods you plan to use\n    -   Ideal: Start trying the methods!\n-   **On Monday - Milestone 4**\n    -   First 30 mins: talk/work as teams\n    -   Last 45 mins: give feedback to another team!\n:::\n\n\n\n\n\n# Yesterday was a lot...\n\nQuick Recap!\n\n## Confusion Matrix {.smaller}\n\n::: columns\n::: {.column width=\"40%\"}\n![](images/c_m.png)\n:::\n\n::: {.column width=\"60%\"}\n::: incremental\n-   False negative rate = $\\frac{FN}{FN + TP}$\n-   False positive rate = $\\frac{FP}{FP + TN}$\n-   Sensitivity = $\\frac{FN}{FN + TP}$ = 1 − False negative rate\n-   Specificity = $\\frac{TN}{FP + TN}$ = 1 - False positive rate\n:::\n:::\n:::\n\n## ROC Curve\n\n![](images/20/roc-curve-annotated.png)\n\n# Quantifying uncertainty\n\n## Samples {.smaller}\n\nGenerally, we don't have information about an entire population, we have data for a sample:\n\n::: incremental\n-   Election polling: we can't ask everybody who they are voting for\n\n-   Housing data: we don't have a data set with every single house\n\n-   Medical research: we don't test a new drug on everyone, just on a sample of patients in a clinical trial.\n\n-   Ecology studies: scientists might analyze a smaller sample of animals/plants\n:::\n\n. . .\n\nThere is uncertainty about true population parameters.\n\n## Statistical inference {.smaller}\n\n::: incremental\n-   **Statistical inference** provide methods and tools so we can use the single observed sample to make valid statements (inferences) about the population it comes from\n\n-   For our inferences to be valid, **the sample should be random** and representative of the population we're interested in\n:::\n\n## Example - Means {.smaller}\n\nSuppose this histogram represents some value $x$ in a population of 10,000:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n\n## Example - Means (Sample Size 2) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.9\n:::\n:::\n:::\n\n## Example - Means (Sample Size 2) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>47.8\n:::\n:::\n:::\n\n## Example - Means (Sample Size 2) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>56.08\n:::\n:::\n:::\n\n## Example - Means (Sample Size 2) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>54.38\n:::\n:::\n:::\n\n## Example - Means (Sample Size 2) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>59.24\n:::\n:::\n:::\n\n## Example - Means (Sample Size 10) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>53.29\n:::\n:::\n:::\n\n## Example - Means (Sample Size 10) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>51.59\n:::\n:::\n:::\n\n## Example - Means (Sample Size 10) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.24\n:::\n:::\n:::\n\n## Example - Means (Sample Size 10) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>57.99\n:::\n:::\n:::\n\n## Example - Means (Sample Size 10) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>56.54\n:::\n:::\n:::\n\n## Example - Means (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.55\n:::\n:::\n:::\n\n## Example - Means (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>54.84\n:::\n:::\n:::\n\n## Example - Means (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>54.98\n:::\n:::\n:::\n\n## Example - Means (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>54.58\n:::\n:::\n:::\n\n## Example - Means (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.57\n:::\n:::\n:::\n\n## Example - Means (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.12\n:::\n:::\n:::\n\n## Example - Means (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.29\n:::\n:::\n:::\n\n## Example - Means (Sample Size 1000) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.07\n:::\n:::\n:::\n\n## Example - Means (Sample Size 1000) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n:::\n\n## Example - Means (Sample Size 1000) {.smaller}\n\n::: columns\n::: {.column width=\"50% \"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.06\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Mean: </strong>55.05\n:::\n:::\n:::\n\n## Example - Means {.smaller}\n\nHow confident would you feel stating that the population mean is equal to any of these values?\n\n## Example - Slopes {.smaller}\n\nSuppose this scatter plot represents some values $x, y$ in a population of 10,000:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n\n## Example - Slopes (Sample Size 2) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>5.97\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 2) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>1.31\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 2) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>2.57\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 2) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>-5.51\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 10) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>1.08\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 10) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>1.01\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 10) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>1.41\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 10) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.45\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-62-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>1.06\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-64-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.68\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-65-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-66-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>1.05\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-67-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-68-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.84\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 100) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-69-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-70-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.64\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 1000) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-71-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-72-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.77\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 1000) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-73-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-74-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.72\n:::\n:::\n:::\n\n## Example - Slopes (Sample Size 1000) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-75-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.81\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-76-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"text-align: center;\"}\n<strong>Slope: </strong>0.82\n:::\n:::\n:::\n\n## Example - Slopes {.smaller}\n\nHow confident would you feel stating that the population slope is equal to any of these values?s\n\n## The Vision {.smaller}\n\nHow can we give a range of reasonable values for the population data using the sample data we have??\n\n::: incremental\n-   ***Idea***: use the sample to take more samples???\n\n-   ***Method***: bootstrapping!\n:::\n\n## Bootstrapping\n\n![](images/bootstrap/1.png){fig-align=\"center\"}\n\n## Bootstrapping\n\n![](images/bootstrap/2.png){fig-align=\"center\"}\n\n## Bootstrapping\n\n![](images/bootstrap/3.png){fig-align=\"center\"}\n\n## Bootstrapping\n\n![](images/bootstrap/4.png){fig-align=\"center\"}\n\n## Bootstrapping\n\n![](images/bootstrap/5.png){fig-align=\"center\"}\n\n## Bootstrapping\n\n![](images/bootstrap/6.png){fig-align=\"center\"}\n\n## Bootstrapping\n\n![](images/bootstrap/7.png){fig-align=\"center\"}\n\n## Today's Goal {.smaller}\n\nFind range of plausible values for a slope using bootstrap confidence intervals.\n\n## Data: Houses in Duke Forest {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n-   Data on houses that were sold in the Duke Forest neighborhood of Durham, NC around November 2020\n-   Pulled from Zillow\n-   Source: [`openintro::duke_forest`](http://openintrostat.github.io/openintro/reference/duke_forest.html)\n:::\n\n::: {.column width=\"50%\"}\n![](images/21/duke_forest_home.jpg){fig-alt=\"Home in Duke Forest\"}\n:::\n:::\n\n. . .\n\n**Goal**: Use the area (in square feet) to understand variability in the price of houses in Duke Forest.\n\n## Exploratory data analysis\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(duke_forest, aes(x = area, y = price)) +\n  geom_point(alpha = 0.7) +\n  labs(\n    x = \"Area (square feet)\",\n    y = \"Sale price (USD)\",\n    title = \"Price and area of houses in Duke Forest\"\n  ) +\n  scale_y_continuous(labels = label_dollar()) \n```\n\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-77-1.png){width=672}\n:::\n:::\n\n\n## Modeling {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_fit <- linear_reg() |>\n  fit(price ~ area, data = duke_forest)\n\ntidy(df_fit) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  116652.   53302.       2.19 3.11e- 2\n2 area            159.      18.2      8.78 6.29e-14\n```\n\n\n:::\n:::\n\n\n. . .\n\n\n::: {.cell}\n\n:::\n\n\n::: incremental\n-   **Intercept:** Duke Forest houses that are 0 square feet are expected to sell, for $116,652, on average.\n\n-   **Slope:** For each additional square foot, we expect the sale price of Duke Forest houses to be higher by $159, on average.\n:::\n\n## From sample to population {.smaller}\n\n> For each additional square foot, we expect the sale price of Duke Forest houses to be higher by $159, on average.\n\n<br>\n\n::: incremental\n-   This estimate is valid for the single sample of 98 houses.\n-   But what if we're not interested quantifying the relationship between the size and price of a house in this single sample?\n-   What if we want to say something about the relationship between these variables for all houses in Duke Forest?\n:::\n\n## Inference for simple linear regression\n\n-   Calculate a confidence interval for the slope, $\\beta_1$ (today)\n\n-   Conduct a hypothesis test for the slope,$\\beta_1$ (next week)\n\n# Confidence interval for the slope\n\n## Confidence interval {.smaller}\n\n::: incremental\n-   A plausible range of values for a population parameter is called a **confidence interval**\n-   Using only a single point estimate is like fishing in a murky lake with a spear. Using a confidence interval is like fishing with a net.\n    -   We can throw a spear where we saw a fish but we will probably miss. If we toss a net in that area, we have a good chance of catching the fish.\n    -   If we report a point estimate, we probably will not hit the exact population parameter. If we report a range of plausible values we have a good shot at capturing the parameter\n:::\n\n## Confidence interval for the slope {.smaller}\n\nA confidence interval will allow us to make a statement like \"*For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $159, plus or minus X dollars.*\"\n\n. . .\n\n-   Should X be \\$10?\n    \\$100?\n    \\$1000?\n\n-   If we were to take another sample of 98 would we expect the slope calculated based on that sample to be exactly $159?\n    Off by \\$10?\n    \\$100?\n    \\$1000?\n\n. . .\n\n-   The answer depends on how variable (from one sample to another sample) the sample statistic (the slope) is\n\n. . .\n\n-   We need a way to quantify the variability of the sample statistic\n\n## Quantify the variability of the slope {.smaller}\n\n::: incremental\n-   Two approaches:\n    1.  Via simulation (what we'll do in this course)\n    2.  Via mathematical models (what you can learn about in future courses)\n:::\n\n## Quantify the variability of the slope {.smaller}\n\n**Bootstrapping** to quantify the variability of the slope for the purpose of estimation:\n\n::: incremental\n-   Bootstrap new samples from the original sample\n-   Fit models to each of the samples and estimate the slope\n-   Use features of the distribution of the bootstrapped slopes to construct a confidence interval\n:::\n\n\n::: {.cell}\n\n:::\n\n\n## Bootstrap sample 1\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-81-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-82-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n## Bootstrap sample 2\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-83-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-84-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n## Bootstrap sample 3\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-85-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-86-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n## Bootstrap sample 4\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-87-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-88-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n## Bootstrap sample 5\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-89-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-90-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n. . .\n\n*so on and so forth...*\n\n## Bootstrap samples 1 - 5\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-91-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-92-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n## Bootstrap samples 1 - 100\n\n\n::: {.cell}\n\n:::\n\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-94-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-95-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n## Slopes of bootstrap samples {.smaller}\n\n**Fill in the blank:** For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $159, plus or minus \\_\\_\\_ dollars.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-96-1.png){width=672}\n:::\n:::\n\n\n## Slopes of bootstrap samples {.smaller}\n\n**Fill in the blank:** For each additional square foot, we expect the sale price of Duke Forest houses to be higher, on average, by $159, plus or minus \\_\\_\\_ dollars.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-97-1.png){width=672}\n:::\n:::\n\n\n## Confidence level {.smaller}\n\nHow confident are you that the true slope is between \\$0 and \\$250?\nHow about \\$150 and \\$170?\nHow about \\$90 and \\$210?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-98-1.png){width=672}\n:::\n:::\n\n\n## 95% confidence interval {.xsmall}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-99-1.png){width=672}\n:::\n:::\n\n\n::: incremental\n-   A 95% confidence interval is bounded by the middle 95% of the bootstrap distribution\n-   We are 95% confident that for each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $90.43 to $205.77.\n:::\n\n# Application exercise\n\n## Calculate observed fit {.smaller}\n\nCalculate the observed slope:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_fit <- duke_forest |>\n  specify(price ~ area) |>\n  fit()\n\nobserved_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  term      estimate\n  <chr>        <dbl>\n1 intercept  116652.\n2 area          159.\n```\n\n\n:::\n:::\n\n\n## Take bootstrap samples {.smaller}\n\nTake `100` bootstrap samples and fit models to each one:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nn = 100\n\nboot_fits <- duke_forest |>\n  specify(price ~ area) |>\n  generate(reps = n, type = \"bootstrap\") |>\n  fit()\n\nboot_fits\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 200 × 3\n# Groups:   replicate [100]\n   replicate term      estimate\n       <int> <chr>        <dbl>\n 1         1 intercept  177388.\n 2         1 area          125.\n 3         2 intercept  161078.\n 4         2 area          150.\n 5         3 intercept  202354.\n 6         3 area          118.\n 7         4 intercept  120750.\n 8         4 area          162.\n 9         5 intercept   52127.\n10         5 area          180.\n# ℹ 190 more rows\n```\n\n\n:::\n:::\n\n\n## Examine bootstrap samples {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboot_fits |>\n  filter(term == \"area\") |>\n  ggplot(aes(x = estimate)) +\n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/unnamed-chunk-102-1.png){width=672}\n:::\n:::\n\n\n## Computing the CI for the slope III {.smaller}\n\n**Percentile method:** Compute the 95% CI as the middle 95% of the bootstrap distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_confidence_interval(\n  boot_fits, \n  point_estimate = observed_fit, \n  level = 0.95,\n  type = \"percentile\" \n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  term      lower_ci upper_ci\n  <chr>        <dbl>    <dbl>\n1 area          92.4     206.\n2 intercept   7014.   285255.\n```\n\n\n:::\n:::\n\n\n## Precision vs. accuracy {.smaller}\n\n::: task\nIf we want to be very certain that we capture the population parameter, should we use a wider or a narrower interval?\nWhat drawbacks are associated with using a wider interval?\n:::\n\n. . .\n\n![](images/21/garfield.png)\n\n## Precision vs. accuracy {.smaller}\n\n::: task\nHow can we get best of both worlds -- high precision and high accuracy?\n:::\n\n## Changing confidence level {.smaller}\n\n::: task\nHow would you modify the following code to calculate a 90% confidence interval?\nHow would you modify it for a 99% confidence interval?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_confidence_interval(\n  boot_fits, \n  point_estimate = observed_fit, \n  level = 0.95,\n  type = \"percentile\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  term      lower_ci upper_ci\n  <chr>        <dbl>    <dbl>\n1 area          92.4     206.\n2 intercept   7014.   285255.\n```\n\n\n:::\n:::\n\n\n## Changing confidence level {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## confidence level: 90%\nget_confidence_interval(\n  boot_fits, point_estimate = observed_fit, \n  level = 0.90, type = \"percentile\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  term      lower_ci upper_ci\n  <chr>        <dbl>    <dbl>\n1 area          96.1     197.\n2 intercept  20626.   268049.\n```\n\n\n:::\n\n```{.r .cell-code}\n## confidence level: 99%\nget_confidence_interval(\n  boot_fits, point_estimate = observed_fit, \n  level = 0.99, type = \"percentile\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  term      lower_ci upper_ci\n  <chr>        <dbl>    <dbl>\n1 area          69.7     214.\n2 intercept -25879.   351614.\n```\n\n\n:::\n:::\n\n\n## Recap {.xsmall}\n\n::: incremental\n-   **Population:** Complete set of observations of whatever we are studying, e.g., people, tweets, photographs, etc. (population size = $N$)\n\n-   **Sample:** Subset of the population, ideally random and representative (sample size = $n$)\n\n-   Sample statistic $\\ne$ population parameter, but if the sample is good, it can be a good estimate\n\n-   **Statistical inference:** Discipline that concerns itself with extracting meaning and information from data that has been generated by random process\n\n-   We report the estimate with a confidence interval.\n    The width of this interval depends on the variability of sample statistics from different samples from the population\n\n-   Since we can't continue sampling from the population, we bootstrap from the one sample we have to estimate sampling variability\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  linear_reg() |>\n    fit(wt ~ cyl + hp, data = mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nparsnip model object\n\n\nCall:\nstats::lm(formula = wt ~ cyl + hp, data = data)\n\nCoefficients:\n(Intercept)          cyl           hp  \n  0.5820880    0.4177733    0.0003422  \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "20-bootstrap_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}